#!/bin/bash
#SBATCH --job-name=ET_ChIP_Heatmap
#SBATCH --partition=batch
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=evt82290@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=50gb
#SBATCH --time=6:00:00
#SBATCH --output=../Heatmap/logs/Heatmap.%j.out
#SBATCH --error=../Heatmap/logs/Heatmap.%j.err

#output directories
OUTDIR1="/scratch/evt82290/Heatmaps/qa-suz12"
OUTDIR2="/scratch/evt82290/RNAseq/CAF-1_Heatmap/bigWig"
OUTDIR3="/scratch/evt82290/MappingOutputs/RNAseq_split/bigWig"

#bigWig directories
P126DIR="/scratch/evt82290/MappingOutputs/Run126/bigWig"
P129DIR="/scratch/evt82290/MappingOutputs/Run129/bigWig"
P131DIR="/scratch/evt82290/MappingOutputs/Run131/bigWig"
P133DIR="/scratch/evt82290/MappingOutputs/Run133/bigWig"
P136DIR="/scratch/evt82290/MappingOutputs/Run136/bigWig"
P137DIR="/scratch/evt82290/MappingOutputs/Run137/bigWig"
P138DIR="/scratch/evt82290/MappingOutputs/Run138/bigWig"
P139DIR="/scratch/evt82290/MappingOutputs/Run139/bigWig"
P141DIR="/scratch/evt82290/MappingOutputs/Run141/bigWig"
P144DIR="/scratch/evt82290/MappingOutputs/Run144/bigWig"
P145DIR="/scratch/evt82290/MappingOutputs/Run145/bigWig"
P146DIR="/scratch/evt82290/MappingOutputs/Run146/bigWig"
P148DIR="/scratch/evt82290/MappingOutputs/Run148/bigWig"
P149DIR="/scratch/evt82290/MappingOutputs/Run149/bigWig"
P150DIR="/scratch/evt82290/MappingOutputs/Run150/bigWig"
MISCDIR="/scratch/evt82290/MappingOutputs/misc_data/bigWig"
RNADIR="/scratch/evt82290/RNAseq/misc_mutants/bigWig"
ATACDIR="/scratch/evt82290/MappingOutputs/ATAC/BigWigs"

#bed file directories
QABED="/home/evt82290/Research/bed_files/qa-suz12"
BEDDIR="/scratch/evt82290/RNAseqIGV/bedgraph"
BEDDIR2="/home/evt82290/Research/bed_files"

#load deeptools
module load deepTools


#############################
# Special strategy for plotting and ordering genes with retained, lost, and gained H3K27me3 in CAF-1 mutants
#
# Plotting ALL qa-suz12 K27 regions (normal & ectopic)
# Step 1: Compute matrices for each BED category
# computeMatrix scale-regions -b 800 --regionBodyLength 2000 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#   -R $BEDDIR2/K27_in_cac1.bed \
#   --skipZeros -o matrix_retained.gz
#
# computeMatrix scale-regions -b 800 --regionBodyLength 2000 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#   -R $BEDDIR2/K27_lost_cac1.bed \
#   --skipZeros -o matrix_lost.gz
#
# computeMatrix scale-regions -b 800 --regionBodyLength 2000 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#   -R $BEDDIR2/K27_gain_cac1.bed \
#   --skipZeros -o matrix_ectopic.gz
#
# # Step 2: Sort with plotHeatmap (not computeMatrixOperations) and export new BEDs
# plotHeatmap -m matrix_retained.gz -out retained_sorted.pdf \
#   --sortRegions descend --sortUsing sum --sortUsingSamples 1 2 \
#   --outFileSortedRegions retained_sorted.bed
#
# plotHeatmap -m matrix_lost.gz -out lost_sorted.pdf \
#   --sortRegions descend --sortUsing sum --sortUsingSamples 1 \
#   --outFileSortedRegions lost_sorted.bed
#
# plotHeatmap -m matrix_ectopic.gz -out ectopic_sorted.pdf \
#   --sortRegions descend --sortUsing sum --sortUsingSamples 2 \
#   --outFileSortedRegions ectopic_sorted.bed
#
#   # Step 3: Fix group column in each sorted BED
#   awk 'BEGIN{OFS="\t"} {$NF="retained"; print}' retained_sorted.bed > retained_grouped.bed
#   awk 'BEGIN{OFS="\t"} {$NF="lost"; print}' lost_sorted.bed > lost_grouped.bed
#   awk 'BEGIN{OFS="\t"} {$NF="gained"; print}' ectopic_sorted.bed > ectopic_grouped.bed
#
# # Step 4: Final matrix using the sorted BEDs as separate region groups
# computeMatrix scale-regions -b 800 --regionBodyLength 2000 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#   -R retained_grouped.bed lost_grouped.bed ectopic_grouped.bed \
#   --skipZeros \
#   -o matrix_CAF-1_K27_clustered.gz
# #
# plotHeatmap -m matrix_CAF-1_K27_clustered.gz -out H3K27me3_CAF-1_K27_clustered_1-5.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "5'" --endLabel "3'" \
#   --missingDataColor 1 \
#   --whatToShow "heatmap and colorbar" \
#   --colorList 'white,g,darkgreen' \
#   --zMin 0 --zMax 50 \
#   --sortRegions no
#
# ###K4
# computeMatrix scale-regions -a 250 -b 800 --regionBodyLength 2000 \
# -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-23_ChIP_set-7_H3K4me2_Rep1_S23.bin_25.smooth_75Bulk.bw \
#   -R retained_grouped.bed lost_grouped.bed ectopic_grouped.bed \
#   --skipZeros \
#   -o matrix_CAF-1_K4_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_K4_clustered.gz -out H3K27me3_CAF-1_K4_clustered_1-5.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "5'" --endLabel "3'" \
#   --missingDataColor 1 \
#   --whatToShow "heatmap and colorbar" \
#   --colorList 'white,magenta' \
#   --zMin 0 \
#   --sortRegions no
#
# ###Kac
# computeMatrix scale-regions -a 250 -b 800 --regionBodyLength 2000 \
# -S $P150DIR/150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-137_ChIP_cac-2_Kac_Rep2_S152.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-139_ChIP_set-7_Kac_Rep2_S154.bin_25.smooth_75Bulk.bw \
#   -R retained_grouped.bed lost_grouped.bed ectopic_grouped.bed \
#   --skipZeros \
#   -o matrix_CAF-1_Kac_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_Kac_clustered.gz -out H3K27me3_CAF-1_Kac_clustered_1-5.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "5'" --endLabel "3'" \
#   --missingDataColor 1 \
#   --whatToShow "heatmap and colorbar" \
#   --colorList 'white, lavender, mediumslateblue' \
#   --zMin 0 \
#   --sortRegions no


##################################

#H3K4me2
#clustered
#     computeMatrix scale-regions -a 500 -b 1000 --regionBodyLength 2000 --scale 1.5 \
#      -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#         $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
#         $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
#         $P146DIR/146-22_ChIP_cac-3_H3K4me2_Rep1_S22.bin_25.smooth_75Bulk.bw \
#         $P146DIR/146-23_ChIP_set-7_H3K4me2_Rep1_S23.bin_25.smooth_75Bulk.bw \
#         -R $BEDDIR2/K27_cluster_stringent.bed --skipZeros -o matrix_PRC2_K4.gz
#
#     plotHeatmap -m matrix_PRC2_K4.gz -out CAF-1_K4_K27genes_CAF-1_clustered.pdf \
#             --samplesLabel WT cac-1 cac-2 cac-3 set-7 \
#             --startLabel "TSS" \
#             --endLabel "TES" \
#             --sortRegions descend \
#             --sortUsingSamples 5 \
#             --missingDataColor 1 \
#             --heatmapHeight 25 \
#             --colorList 'white, violet, magenta' \
#             --zMin 0 \






# All K4 genes
    # computeMatrix scale-regions -a 250 -b 250 --regionBodyLength 2000 --scale 1.5 \
    #  -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
    #     $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
    #     $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
    #     $P146DIR/146-23_ChIP_set-7_H3K4me2_Rep1_S23.bin_25.smooth_75Bulk.bw \
    #     $P146DIR/146-22_ChIP_cac-3_H3K4me2_Rep1_S22.bin_25.smooth_75Bulk.bw \
    #     -R $BEDDIR2/K4_genes_gff.bed --skipZeros -o matrix_PRC2_K4.gz
    #
    # plotHeatmap -m matrix_PRC2_K4.gz -out CAF-1_K4_genes.pdf \
    #         --samplesLabel WT cac-1 cac-2 set-7 cac-3 \
    #         --startLabel "TSS" \
    #         --endLabel "TES" \
    #         --sortRegions descend \
    #         --missingDataColor 1 \
    #         --heatmapHeight 25 \
    #         --colorMap 'cool' \
    #         --zMin 0 \


# #cac-2 comp (K4)
# computeMatrix scale-regions -a 250 -b 250 \
#                      -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#                         $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
#                         $P149DIR/149-128_ChIP_cac-2_comp_H3K4me2_Rep1_S152.bin_25.smooth_75Bulk.bw \
#                         -R $BEDDIR2/cac-2_ectopic_K4_genes.bed --skipZeros -o matrix_PRC2_cac2_comp.gz
#
#                         plotHeatmap -m matrix_PRC2_cac2_comp.gz -out cac-2_comp_K4_regions.pdf \
#                                         --samplesLabel WT cac-2 comp \
#                                         --startLabel "TSS" \
#                                         --endLabel "TES" \
#                                         --sortRegions descend \
#                                         --sortUsingSamples 1 \
#                                         --missingDataColor 1 \
#                                         --colorList 'white, violet, magenta' \
#                                         --zMin 0 \

                                        # 146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw
                                        # 146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw
                                        # 149-128_ChIP_cac-2_comp_H3K4me2_Rep1_S152.bin_25.smooth_75Bulk.bw
                                        # 149-129_ChIP_cac-2_comp_H3K4me2_Rep1_S153.bin_25.smooth_75Bulk.bw

# #unclustered
#
# #H3K9me3
# #clustered
# computeMatrix scale-regions -a 1000 -b 1000 \
#  -S $P149DIR/149-104_ChIP_WT_H3K9me3_Rep3_S128.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-105_ChIP_cac-1_H3K9me3_Rep3_S129.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-106_ChIP_cac-2_H3K9me3_Rep3_S130.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-107_ChIP_cac-3_H3K9me3_Rep3_S131.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-108_ChIP_set-7_Input_Rep3_S132.bin_25.smooth_75Bulk.bw \
#     -R $BEDDIR2/WT_H3K9me3_Rep1_peaks.bed --skipZeros -o K9_matrix_PRC2.gz
#
#     plotHeatmap -m K9_matrix_PRC2.gz -out CAF-1_K9_regions.pdf \
#                     --samplesLabel WT cac-1 cac-2 cac3 set-7 \
#                     --startLabel "TSS" \
#                     --endLabel "TES" \
#                     --sortUsing sum \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 \
#                     --missingDataColor 1 \
#                     --heatmapHeight 15 \
#                     --outFileSortedRegions heatmap.bed \
#                     --colorList 'white, mediumblue' \
#                     --zMin 0 \

                    # $P133DIR/133-23_ChIP_WT_H3K9me3_Rep2_S21.bin_25.smooth_75Bulk.bw \
                    # $P133DIR/133-24_ChIP_cac-1_H3K9me3_Rep2_S22.bin_25.smooth_75Bulk.bw  \
                    # $P133DIR/133-25_ChIP_cac-2_H3K9me3_Rep2_S23.bin_25.smooth_75Bulk.bw \
                    # 149-104_ChIP_WT_H3K9me3_Rep3_S128.bin_25.smooth_75Bulk.bw
                    # 149-105_ChIP_cac-1_H3K9me3_Rep3_S129.bin_25.smooth_75Bulk.bw
                    # 149-106_ChIP_cac-2_H3K9me3_Rep3_S130.bin_25.smooth_75Bulk.bw
                    # 149-107_ChIP_cac-3_H3K9me3_Rep3_S131.bin_25.smooth_75Bulk.bw
                    # 149-108_ChIP_set-7_Input_Rep3_S132.bin_25.smooth_75Bulk.bw

#unclustered

#H3K36me3
#clustered
computeMatrix scale-regions -a 800 --regionBodyLength 2000 --scale 1.5 \
 -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
    $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
    $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
    $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
    $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
    -R $BEDDIR2/H3K36me3_methylated_genes_WT_genes.bed --missingDataAsZero --skipZeros -o K36_matrix_PRC2.gz

    plotHeatmap -m K36_matrix_PRC2.gz -out CAF-1_ash1_H3K36me3_K27genes_CAF-1_clustered.pdf \
                    --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
                    --startLabel "TSS" \
                    --endLabel "TES" \
                    --sortRegions descend \
                    --sortUsingSamples 1 \
                    --heatmapHeight 25 \
                    --colorMap "afmhot_r" \
                    --zMin 0 --zMax 18

    # $P149DIR/149-102_ChIP_cac-3_H3K36me3_Rep3_S126.bin_25.smooth_75Bulk.bw \

# computeMatrix scale-regions -a 250 -b 1000 --regionBodyLength 2000 --scale 1.5
## unclustered
# computeMatrix scale-regions -b 800 --regionBodyLength 2000 --scale 2 \
#  -S $P150DIR/150-93_ChIP_WT_H3K36me3_Rep4_S93.bin_25.smooth_75Bulk.bw \
#     $P150DIR/150-94_ChIP_cac-1_H3K36me3_Rep4_S94.bin_25.smooth_75Bulk.bw \
#     $P150DIR/150-116_ChIP_cac-2_H3K36me3_Rep4_S131.bin_25.smooth_75Bulk.bw \
#     $P150DIR/150-134_ChIP_set-7_H3K36me3_Rep4_S149.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     -R $BEDDIR2/H3K36me3_no_ash1_noK27.bed --skipZeros -o K36_matrix_PRC2_1.gz
#
#     plotHeatmap -m K36_matrix_PRC2_1.gz -out H3K36me3_no_ash1_CAFmutants.pdf \
#                     --samplesLabel WT cac-1 cac-2 set-7 ash-1 \
#                     --startLabel "TSS" \
#                     --endLabel "TES" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 2 3 5 \
#                     --missingDataColor 1 \
#                     --colorMap "afmhot_r" \
#                     --heatmapHeight 20 \
#                     --zMin 0 \
#                     --zMax 18

# $BEDDIR2/CAF-1_H3K36me3_lost_K27_genes.bed $BEDDIR2/CAF-1_H3K36me3_not_lost_K27_genes.bed

#$P138DIR/138-65_ChIP_cac-3_H3K36me3_Rep2_6252_S64.bin_25.smooth_75Bulk.bw \

# computeMatrix scale-regions -a 250 -b 800 --regionBodyLength 2000 --scale 2 \
#  -S $P150DIR/150-93_ChIP_WT_H3K36me3_Rep4_S93.bin_25.smooth_75Bulk.bw \
#     $P150DIR/150-94_ChIP_cac-1_H3K36me3_Rep4_S94.bin_25.smooth_75Bulk.bw \
#     $P150DIR/150-116_ChIP_cac-2_H3K36me3_Rep4_S131.bin_25.smooth_75Bulk.bw \
#     $P150DIR/150-134_ChIP_set-7_H3K36me3_Rep4_S149.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     -R $BEDDIR2/K27_silent_genes.bed --skipZeros -o K36_matrix_PRC2_2.gz
#
#     plotHeatmap -m K36_matrix_PRC2_2.gz -out CAF-1_ash1_H3K36me3_K27_silent_genes.pdf \
#                     --samplesLabel WT cac-1 cac-2 set-7 ash-1 \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 2 \
#                     --missingDataColor 1 \
#                     --boxAroundHeatmaps no \
#                     --heatmapHeight 20 \
#                     --colorMap "afmhot" \
#                     --zMin 0 \
#                     --zMax 20 \

                    # 150-116_ChIP_cac-2_H3K36me3_Rep4_S131.bin_25.smooth_75Bulk.bw
                    # 150-131_ChIP_cac-3_H3K36me3_Rep4_S146.bin_25.smooth_75Bulk.bw
                    # 150-134_ChIP_set-7_H3K36me3_Rep4_S149.bin_25.smooth_75Bulk.bw
                    # 150-93_ChIP_WT_H3K36me3_Rep4_S93.bin_25.smooth_75Bulk.bw
                    # 150-94_ChIP_cac-1_H3K36me3_Rep4_S94.bin_25.smooth_75Bulk.bw

# #138-62_ChIP_WT_H3K36me3_Rep2_6252_S61.bin_25.smooth_75Bulk.bw
# #138-63_ChIP_cac-1_H3K36me3_Rep2_6252_S62.bin_25.smooth_75Bulk.bw
# #138-64_ChIP_cac-2_H3K36me3_Rep2_6252_S63.bin_25.smooth_75Bulk.bw
# #138-65_ChIP_cac-3_H3K36me3_Rep2_6252_S64.bin_25.smooth_75Bulk.bw
# #138-66_ChIP_set-7_H3K36me3_Rep2_6252_S65.bin_25.smooth_75Bulk.bw
#
# # 149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw
# # 149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw
# # 149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw
# # 149-102_ChIP_cac-3_H3K36me3_Rep3_S126.bin_25.smooth_75Bulk.bw
# # 149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw
#
# #H4K20me3
# #clustered
# computeMatrix scale-regions -a 500 -b 1000 --regionBodyLength 2000 --scale 1.5 \
#  -S $P133DIR/133-19_ChIP_WT_H4K20me3_Rep1_S17.bin_25.smooth_75Bulk.bw \
#     $P133DIR/133-20_ChIP_cac-1_H4K20me3_Rep1_S18.bin_25.smooth_75Bulk.bw \
#     $P133DIR/133-21_ChIP_cac-2_H4K20me3_Rep1_S19.bin_25.smooth_75Bulk.bw \
#     $P133DIR/133-22_ChIP_set-7_H4K20me3_Rep1_S20.bin_25.smooth_75Bulk.bw  \
#     -R $BEDDIR2/K27_cluster_stringent.bed --skipZeros -o H4K20_matrix_PRC2.gz
#
#     plotHeatmap -m H4K20_matrix_PRC2.gz -out CAF-1_H4K20me3_K27genes_CAF-1_clustered.pdf \
#                     --samplesLabel WT cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --endLabel "TES" \
#                     --sortRegions descend \
#                     --missingDataColor 1 \
#                     --colorList 'white, blueviolet' \
#                     --zMin 0 \
#
# #unclustered
#
#ATAC
#clustered
# computeMatrix scale-regions -a 250 -b 1250 --regionBodyLength 2000 --scale 1.5 \
#  -S $ATACDIR/148-N14_ATAC_WT__Rep3.ATAC_bin_3.smooth_6_Bulk.bw \
#     $ATACDIR/148-N15_ATAC_cac-1__Rep3.ATAC_bin_3.smooth_6_Bulk.bw \
#     $ATACDIR/148-N16_ATAC_cac-2__Rep3.ATAC_bin_3.smooth_6_Bulk.bw \
#     $ATACDIR/148-N17_ATAC_cac-3__Rep3.ATAC_bin_3.smooth_6_Bulk.bw \
#     $ATACDIR/148-N19_ATAC_set-7__Rep3.ATAC_bin_3.smooth_6_Bulk.bw \
#     -R $BEDDIR2/nonK27_genes.bed --skipZeros -o matrix_PRC2_1.gz
#
#     plotHeatmap -m matrix_PRC2_1.gz -out CAF-1_ATAC_Rep3_nonK27genes.pdf \
#                     --samplesLabel WT cac-1 cac-2 cac-3 set-7 \
#                     --startLabel "TSS" \
#                     --endLabel "TES" \
#                     --sortRegions descend \
#                     --missingDataColor 1 \
#                     --colorMap "bwr" \
#                     --zMin 0

# #unclustered
#
# #$P148DIR/148-N14_ATAC_WT__Rep3_S110.bin_25.smooth_75Bulk.bw
# #$P148DIR/148-N15_ATAC_cac-1__Rep3_S111.bin_25.smooth_75Bulk.bw
# #$P148DIR/148-N16_ATAC_cac-2__Rep3_S112.bin_25.smooth_75Bulk.bw
# #$P148DIR/148-N17_ATAC_cac-3__Rep3_S113.bin_25.smooth_75Bulk.bw
# #$P148DIR/148-N19_ATAC_set-7__Rep3_S115.bin_25.smooth_75Bulk.bw
#
# #$P148DIR/148-N20_ATAC_WT__Rep4_S116.bin_25.smooth_75Bulk.bw
# #148-N21_ATAC_cac-1__Rep4_S117.bin_25.smooth_75Bulk.bw
# #148-N22_ATAC_cac-2__Rep4_S118.bin_25.smooth_75Bulk.bw
# #148-N23_ATAC_cac-3__Rep4_S119.bin_25.smooth_75Bulk.bw
# #148-N24_ATAC_set-7__Rep4_S120.bin_25.smooth_75Bulk.bw
#
# # $P141DIR/141-N11_ATAC_WT__Rep1_S100.bin_25.smooth_75Bulk.bw \
# # $P141DIR/141-N12_ATAC_cac-1__Rep1_S101.bin_25.smooth_75Bulk.bw \
# # $P141DIR/141-N13_ATAC_cac-2__Rep1_S102.bin_25.smooth_75Bulk.bw \
# # $P141DIR/141-N14_ATAC_cac-3__Rep1_S103.bin_25.smooth_75Bulk.bw \
# # $P141DIR/141-N15_ATAC_set-7__Rep1_S104.bin_25.smooth_75Bulk.bw \
#
# # $P146DIR/146-N1_ATAC_WT__Rep2_S97.bin_25.smooth_75Bulk.bw
# # $P146DIR/146-N3_ATAC_cac-1__Rep2_S98.bin_25.smooth_75Bulk.bw
# # $P146DIR/146-N4_ATAC_cac-2__Rep2_S99.bin_25.smooth_75Bulk.bw
# # $P146DIR/146-N5_ATAC_set-7__Rep2_S100.bin_25.smooth_75Bulk.bw
# # 146-N6_ATAC_cac-3__Rep2_S101.bin_25.smooth_75Bulk.bw
#
# #H3K27me3
# #clustered
#                     computeMatrix scale-regions -a 500 -b 1000 --regionBodyLength 2000 \
#                      -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#                         $MISCDIR/ash1_H3K27me2me3_Rep2.bin_25.smooth_75Bulk.bw  \
#                         $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#                         $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#                         $P136DIR/6147_136-81_ChIP_cac-3_H3K27me3_CS_Rep2_S80.bin_25.smooth_75Bulk.bw \
#                         $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#                         -R $BEDDIR2/K27genes_in_cac1_2_3_new.bed $BEDDIR2/K27genes_NOT_in_cac1_2_new.bed $BEDDIR2/K27genes_in_cac1_2_NOT_in_cac3_new.bed --skipZeros -o matrix_PRC2_2.gz
#
#                         plotHeatmap -m matrix_PRC2_2.gz -out CAF-1_ash1_K27_K27genes_clustered_NEW.pdf \
#                                 --samplesLabel WT ash-1 cac-1 cac-2 cac-3 set-7 \
#                                 --startLabel "TSS" \
#                                 --endLabel "TES" \
#                                 --missingDataColor 1 \
#                                 --sortUsingSamples 1 3 4 5 6 \
#                                 --outFileSortedRegions heatmap.bed \
#                                 --heatmapHeight 25 \
#                                 --colorList 'white, g, darkgreen' \
#                                 --zMin 0 \
#
# #unclustered
#
# #K27 w new rtt106 data
#                     # computeMatrix scale-regions -a 500 -b 1000 --regionBodyLength 2000 \
#                     #  -S $P149DIR/149-63_ChIP_WT_H3K27me3__S63.bin_25.smooth_75Bulk.bw \
#                     #     $P149DIR/149-68_ChIP_rtt106_H3K27me3_Rep2_S68.bin_25.smooth_75Bulk.bw \
#                     #     $P149DIR/149-64_ChIP_cac-1_H3K27me3__S64.bin_25.smooth_75Bulk.bw \
#                     #     $P149DIR/149-69_ChIP_cac-1-rtt106_H3K27me3_Rep2_S69.bin_25.smooth_75Bulk.bw \
#                     #     $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#                     #     $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#                     #     -R $BEDDIR2/K27_cluster_stringent.bed --skipZeros -o matrix_PRC2_rtt.gz
#                     #
#                     #     plotHeatmap -m matrix_PRC2_rtt.gz -out CAF-1_rtt106_K27_regions_TEST.pdf \
#                     #                     --samplesLabel WT rtt106 cac-1 cac-1_rtt106 cac-2 set-7 \
#                     #                     --startLabel "TSS" \
#                     #                     --endLabel "TES" \
#                     #                     --sortRegions descend \
#                     #                     --missingDataColor 1 \
#                     #                     --colorList "white, g, darkgreen" \
#                     #                     --zMin 0 \
#
#                                         # 149-63_ChIP_WT_H3K27me3__S63.bin_25.smooth_75Bulk.bw
#                                         # 149-64_ChIP_cac-1_H3K27me3__S64.bin_25.smooth_75Bulk.bw
#                                         # 149-68_ChIP_rtt106_H3K27me3_Rep2_S68.bin_25.smooth_75Bulk.bw
#                                         # 149-69_ChIP_cac-1-rtt106_H3K27me3_Rep2_S69.bin_25.smooth_75Bulk.bw
#
#                                         # 149-55_ChIP_WT_H3K27me3__S55.bin_25.smooth_75Bulk.bw
#                                         # 149-56_ChIP_cac-1_H3K27me3__S56.bin_25.smooth_75Bulk.bw
#                                         # 149-57_ChIP_rtt106_H3K27me3_Rep1_S57.bin_25.smooth_75Bulk.bw
#                                         # 149-58_ChIP_cac-1-rtt106_H3K27me3_Rep1_S58.bin_25.smooth_75Bulk.bw
#
# #cac-2 complement (K27)

# computeMatrix scale-regions -a 250 -b 250 \
#                      -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#                         $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#                         $P149DIR/149-123_ChIP_cac-2_comp_H3K27me3_Rep1_S147.bin_25.smooth_75Bulk.bw \
#                         $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#                         -R $BEDDIR2/WT_K27_peaks_IN_cac2.bed $BEDDIR2/WT_K27_peaks_NO_cac2.bed $BEDDIR2/cac-2_ectopic_K27_peaks.bed --skipZeros -o matrix_PRC2_cac2_comp_K27.gz
#
#                         plotHeatmap -m matrix_PRC2_cac2_comp_K27.gz -out cac-2_comp_K27_regions.pdf \
#                                         --samplesLabel WT cac-2 comp set-7 \
#                                         --startLabel "5'" \
#                                         --endLabel "3'" \
#                                         --sortRegions descend \
#                                         --sortUsingSamples 1 2 \
#                                         --missingDataColor 1 \
#                                         --colorList "white, g, darkgreen" \
#                                         --zMin 0 \

                                        # 149-122_ChIP_cac-2_comp_H3K27me3_Rep1_S146.bin_25.smooth_75Bulk.bw
                                        # 149-123_ChIP_cac-2_comp_H3K27me3_Rep1_S147.bin_25.smooth_75Bulk.bw


# #K27ac
# #clustered
#                   computeMatrix scale-regions -a 500 -b 2500 --regionBodyLength 2500 --scale 1.5 \
#                      -S $P149DIR/149-79_ChIP_WT_H3K27ac_Rep2_S79.bin_25.smooth_75Bulk.bw \
#                         $MISCDIR/WT_H3K27ac.bin_25.smooth_75Bulk.bw \
#                         $MISCDIR/ash-1_H3K27ac.bin_25.smooth_75Bulk.bw \
#                         $P149DIR/149-80_ChIP_cac-1_H3K27ac_Rep2_S80.bin_25.smooth_75Bulk.bw \
#                         $P149DIR/149-81_ChIP_cac-2_H3K27ac_Rep2_S81.bin_25.smooth_75Bulk.bw \
#                         $P149DIR/149-82_ChIP_cac-3_H3K27ac_Rep2_S82.bin_25.smooth_75Bulk.bw \
#                         $P149DIR/149-83_ChIP_set-7_H3K27ac_Rep2_S83.bin_25.smooth_75Bulk.bw \
#                         -R $BEDDIR2/K27_cluster_stringent.bed --skipZeros -o matrix_PRC2_K27ac.gz
#
#                         plotHeatmap -m matrix_PRC2_K27ac.gz -out CAF-1_ash1_K27ac_K27_genes_CAF-1_clustered.pdf \
#                                         --samplesLabel WT WT_ash-1 ash-1 cac-1 cac-2 cac-3 set-7 \
#                                         --startLabel "TSS" \
#                                         --endLabel "TES" \
#                                         --sortRegions descend \
#                                         --sortUsingSamples 1 2 \
#                                         --missingDataColor 1 \
#                                         --colorList "white, lavender, mediumslateblue" \
#                                         --zMin 0 \

#Pan Kac
#clustered
                  # computeMatrix scale-regions -a 500 -b 2500 --regionBodyLength 2500 --scale 1.5 \
                  #    -S $P150DIR/150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw \
                  #       $MISCDIR/ash-1_H3K27ac.bin_25.smooth_75Bulk.bw \
                  #       $P150DIR/150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw \
                  #       $P150DIR/150-137_ChIP_cac-2_Kac_Rep2_S152.bin_25.smooth_75Bulk.bw \
                  #       $P150DIR/150-138_ChIP_cac-3_Kac_Rep2_S153.bin_25.smooth_75Bulk.bw \
                  #       $P150DIR/150-139_ChIP_set-7_Kac_Rep2_S154.bin_25.smooth_75Bulk.bw \
                  #       -R $BEDDIR2/K27genes_CAF-1_clustered.bed --skipZeros -o matrix_PRC2_Kac.gz
                  #
                  #       plotHeatmap -m matrix_PRC2_Kac.gz -out CAF-1_Kac_K27_genes_CAF-1_clustered.pdf \
                  #                       --samplesLabel WT ash-1 cac-1 cac-2 cac-3 set-7 \
                  #                       --startLabel "TSS" \
                  #                       --endLabel "TES" \
                  #                       --sortRegions no \
                  #                       --missingDataColor 1 \
                  #                       --colorList "white, lavender, mediumslateblue" \
                  #                       --zMin 0 \



# #unclustered
#
# #RNA-seq
# #clustered
# computeMatrix scale-regions -a 200 -b 200 --regionBodyLength 2000 --scale 3 \
#       -S $OUTDIR2/SRR8269825_log.bw \
#          $RNADIR/set2_RNAseq_ash1paper_1Rep_log.bw \
#          $RNADIR/SRR7690268_log.bw \
#          /scratch/evt82290/MappingOutputs/Run149/RNA/bigWig/149-115_RNA_cac-1__Rep1_S139/149-115_RNA_cac-1__Rep1_S139_log.bw \
#          $OUTDIR2/SRR7970629_log.bw \
#          $OUTDIR2/SRR7970598_log.bw \
#          $OUTDIR2/SRR10916163_log.bw \
#          -R $BEDDIR2/K27_cluster_stringent.bed --skipZeros -o matrix_PRC2_RNA.gz
#
#     plotHeatmap -m matrix_PRC2_RNA.gz -out CAF-1_ash1_RNA-seq_K27genes_CAF-1_clustered.pdf \
#             --samplesLabel WT set-2 ash-1 cac-1 cac-2 cac-3 set-7 \
#             --startLabel "TSS" \
#             --endLabel "TES" \
#             --sortRegions descend \
#             --sortUsingSamples 1 \
#             --missingDataColor 1 \
#             --heatmapHeight 25 \
#             --colorMap "bwr" \
#             --zMin 0 \

###CRYPTIC TRANSCRIPTS

# computeMatrix scale-regions -b 1500 -a 1500 --regionBodyLength 4500 \
#   -S $OUTDIR3/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84.antisense.log2p1.bw \
#      $OUTDIR3/149-116_RNA_cac-1__Rep2_S140/149-116_RNA_cac-1__Rep2_S140.antisense.log2p1.bw \
#      $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.antisense.log2p1.bw \
#      $OUTDIR3/SRR5177527/SRR5177527.antisense.log2p1.bw \
#      $OUTDIR3/SRR5177521/SRR5177521.antisense.log2p1.bw \
#   -R $BEDDIR2/minus_genes.bed $BEDDIR2/plus_genes.bed --skipZeros --missingDataAsZero -o allGenes_antisense.gz
#
# computeMatrix scale-regions -b 1500 -a 1500 --regionBodyLength 4500 --scale 2 \
#   -S $OUTDIR3/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84.antisense.log2p1.bw \
#      $OUTDIR3/149-116_RNA_cac-1__Rep2_S140/149-116_RNA_cac-1__Rep2_S140.antisense.log2p1.bw \
#      $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.antisense.log2p1.bw \
#      $OUTDIR3/SRR5177527/SRR5177527.antisense.log2p1.bw \
#      $OUTDIR3/SRR5177521/SRR5177521.antisense.log2p1.bw \
#   -R $BEDDIR2/K27_genes_minus.bed $BEDDIR2/K27_genes_plus.bed --skipZeros --missingDataAsZero -o K27genes_antisense.gz

#   computeMatrix reference-point --referencePoint TES -a 1500 -b 1500 \
#     -S $OUTDIR3/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84.antisense.log2p1.bw \
#        $OUTDIR3/149-116_RNA_cac-1__Rep2_S140/149-116_RNA_cac-1__Rep2_S140.antisense.log2p1.bw \
#        $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.antisense.log2p1.bw \
#        $OUTDIR3/SRR5177527/SRR5177527.antisense.log2p1.bw \
#        $OUTDIR3/SRR5177521/SRR5177521.antisense.log2p1.bw \
#     -R $BEDDIR2/minus_genes.bed $BEDDIR2/plus_genes.bed --skipZeros --missingDataAsZero -o allGenes_antisense_TES.gz
#
#   computeMatrix reference-point --referencePoint TES -a 1500 -b 1500 --scale 2 \
#     -S $OUTDIR3/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84.antisense.log2p1.bw \
#        $OUTDIR3/149-116_RNA_cac-1__Rep2_S140/149-116_RNA_cac-1__Rep2_S140.antisense.log2p1.bw \
#        $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.antisense.log2p1.bw \
#        $OUTDIR3/SRR5177527/SRR5177527.antisense.log2p1.bw \
#        $OUTDIR3/SRR5177521/SRR5177521.antisense.log2p1.bw \
#     -R $BEDDIR2/K27_genes_minus.bed $BEDDIR2/K27_genes_plus.bed --skipZeros --missingDataAsZero -o K27genes_antisense_TES.gz
#
# plotHeatmap -m allGenes_antisense.gz -out allgenes_dev_antisense.pdf \
#             --samplesLabel WT cac-1 cac-1_suz12 3_dpf 6_dpf \
#             --startLabel "TSS" \
#             --endLabel "TES" \
#             --sortRegions descend \
#             --colorMap "bwr" \
#             --heatmapHeight 20 \
#             --zMin 0 --zMax 3
#
# plotHeatmap -m K27genes_antisense.gz -out K27genes_dev_antisense.pdf \
#             --samplesLabel WT cac-1 cac-1_suz12 3_dpf 6_dpf \
#             --startLabel "TSS" \
#             --endLabel "TES" \
#             --sortRegions descend \
#             --colorMap "bwr" \
#             --legendLocation none \
#             --heatmapHeight 20 \
#             --zMin 0 --zMax 3
#
# plotHeatmap -m allGenes_antisense_TES.gz -out allgenes_dev_antisense_TES.pdf \
#             --samplesLabel WT cac-1 cac-1_suz12 3_dpf 6_dpf \
#             --startLabel "TSS" \
#             --endLabel "TES" \
#             --sortRegions descend \
#             --colorMap "bwr" \
#             --heatmapHeight 20 \
#             --zMin 0 --zMax 3
#
# plotHeatmap -m K27genes_antisense_TES.gz -out K27genes_dev_antisense_TES.pdf \
#             --samplesLabel WT cac-1 cac-1_suz12 3_dpf 6_dpf \
#             --startLabel "TSS" \
#             --endLabel "TES" \
#             --sortRegions descend \
#             --colorMap "bwr" \
#             --legendLocation none \
#             --heatmapHeight 20 \
#             --zMin 0 --zMax 3

#5' sites
# computeMatrix scale-regions -b 1000 -a 1000 --regionBodyLength 4000 \
#   -S $OUTDIR3/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84.forward.5prime.cpm.bw \
#      $OUTDIR3/SRR10916163/SRR10916163.forward.5prime.cpm.bw \
#      $OUTDIR3/149-116_RNA_cac-1__Rep2_S140/149-116_RNA_cac-1__Rep2_S140.forward.5prime.cpm.bw \
#      $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.forward.5prime.cpm.bw \
#   -R $BEDDIR2/plus_genes.bed --skipZeros --missingDataAsZero -o plus_body_5prime.gz
#
# computeMatrix scale-regions -b 1000 -a 1000 --regionBodyLength 4000 \
#   -S $OUTDIR3/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84.reverse.5prime.cpm.bw \
#      $OUTDIR3/SRR10916163/SRR10916163.reverse.5prime.cpm.bw \
#      $OUTDIR3/149-116_RNA_cac-1__Rep2_S140/149-116_RNA_cac-1__Rep2_S140.reverse.5prime.cpm.bw \
#      $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.reverse.5prime.cpm.bw \
#   -R $BEDDIR2/minus_genes.bed --skipZeros --missingDataAsZero -o minus_body_5prime.gz
#
# computeMatrix scale-regions -b 1000 -a 1000 --regionBodyLength 4000 \
#   -S $OUTDIR3/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84.forward.5prime.cpm.bw \
#      $OUTDIR3/SRR10916163/SRR10916163.forward.5prime.cpm.bw \
#      $OUTDIR3/149-116_RNA_cac-1__Rep2_S140/149-116_RNA_cac-1__Rep2_S140.forward.5prime.cpm.bw \
#      $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.forward.5prime.cpm.bw \
#   -R $BEDDIR2/K27_genes_plus.bed --skipZeros --missingDataAsZero -o K27_plus_body_5prime.gz
#
# computeMatrix scale-regions -b 1000 -a 1000 --regionBodyLength 4000 \
#   -S $OUTDIR3/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84.reverse.5prime.cpm.bw \
#      $OUTDIR3/SRR10916163/SRR10916163.reverse.5prime.cpm.bw \
#      $OUTDIR3/149-116_RNA_cac-1__Rep2_S140/149-116_RNA_cac-1__Rep2_S140.reverse.5prime.cpm.bw \
#      $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.reverse.5prime.cpm.bw \
#   -R $BEDDIR2/K27_genes_minus.bed --skipZeros --missingDataAsZero -o K27_minus_body_5prime.gz
#
#     plotHeatmap -m plus_body_5prime.gz -out plus_5prime.pdf \
#                 --samplesLabel WT_new set-7 cac-1_new cac-1_suz12 \
#                 --startLabel "TSS" \
#                 --endLabel "TES" \
#                 --sortRegions descend \
#                 --colorList "blue, red" \
#                 --legendLocation none \
#                 --heatmapHeight 20 \
#                 --zMin 0
#
#     plotHeatmap -m minus_body_5prime.gz -out minus_5prime.pdf \
#                 --samplesLabel WT_new set-7 cac-1_new cac-1_suz12 \
#                 --startLabel "TSS" \
#                 --endLabel "TES" \
#                 --sortRegions descend \
#                 --colorList "blue, red" \
#                 --legendLocation none \
#                 --heatmapHeight 20 \
#                 --zMin 0
#
#     plotHeatmap -m K27_plus_body_5prime.gz -out K27_plus_5prime.pdf \
#                 --samplesLabel WT_new set-7 cac-1_new cac-1_suz12 \
#                 --startLabel "TSS" \
#                 --endLabel "TES" \
#                 --sortRegions descend \
#                 --colorList "blue, red" \
#                 --legendLocation none \
#                 --heatmapHeight 20 \
#                 --zMin 0
#
#     plotHeatmap -m K27_minus_body_5prime.gz -out K27_minus_5prime.pdf \
#                 --samplesLabel WT_new set-7 cac-1_new cac-1_suz12 \
#                 --startLabel "TSS" \
#                 --endLabel "TES" \
#                 --sortRegions descend \
#                 --colorList "blue, red" \
#                 --legendLocation none \
#                 --heatmapHeight 20 \
#                 --zMin 0


# computeMatrix scale-regions -b 500 -a 500 --regionBodyLength 3000 \
#   -S $OUTDIR3/SRR8269825/SRR8269825.forward.cpm.bw \
#      $OUTDIR3/SRR10916163/SRR10916163.forward.cpm.bw \
#      $OUTDIR3/149-115_RNA_cac-1__Rep1_S139/149-115_RNA_cac-1__Rep1_S139.forward.cpm.bw \
#      $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.forward.cpm.bw \
#   -R $BEDDIR2/minus_genes.bed --skipZeros -o minus_genes_antisense.gz

# plotHeatmap -m minus_genes_antisense.gz -out minus_genes_antisense.pdf \
#             --samplesLabel WT set-7 cac-1 cac-1_suz12 \
#             --startLabel "TSS" \
#             --endLabel "TES" \
#             --sortRegions descend \
#             --missingDataColor 1 \
#             --colorMap "bwr" \
#             --zMin 0 \
#
# computeMatrix scale-regions -b 500 -a 500 --regionBodyLength 3000 \
#   -S $OUTDIR3/SRR8269825/SRR8269825.reverse.cpm.bw \
#      $OUTDIR3/SRR10916163/SRR10916163.reverse.cpm.bw \
#      $OUTDIR3/149-115_RNA_cac-1__Rep1_S139/149-115_RNA_cac-1__Rep1_S139.reverse.cpm.bw \
#      $OUTDIR3/149-97_RNA_cac-1-suz-12__Rep2_S121/149-97_RNA_cac-1-suz-12__Rep2_S121.reverse.cpm.bw \
#   -R $BEDDIR2/plus_genes.bed --skipZeros -o plus_genes_antisense.gz
#
# plotHeatmap -m plus_genes_antisense.gz -out plus_genes_antisense.pdf \
#             --samplesLabel WT set-7 cac-1 cac-1_suz12 \
#             --startLabel "TSS" \
#             --endLabel "TES" \
#             --sortRegions descend \
#             --missingDataColor 1 \
#             --colorMap "bwr" \
#             --zMin 0 \



#unclustered

#BEDS
#CAF-1_Ectopic_K27.bed

#Run137
# 137-60_ChIP_WT_HA_Rep1_S57.bin_25.smooth_75Bulk.bw
# 137-61_ChIP_ETX51-cac-1-HA_HA_Rep1_S58.bin_25.smooth_75Bulk.bw
# 137-62_ChIP_ETX52-cac-1-HA_HA_Rep1_S59.bin_25.smooth_75Bulk.bw
# 137-63_ChIP_WT_input__S60.bin_25.smooth_75Bulk.bw
# 137-64_ChIP_ETX51-cac-1-HA_input__S61.bin_25.smooth_75Bulk.bw
# 137-65_ChIP_ETX52-cac-1-HA_input__S62.bin_25.smooth_75Bulk.bw
# 137-66_ChIP_WT_H3K27me3_Rep1_S63.bin_25.smooth_75Bulk.bw
# 137-67_ChIP_qa-suz12_H3K27me3_Rep1_S64.bin_25.smooth_75Bulk.bw
# 137-68_ChIP_WT_H3K27me3_Rep1_S65.bin_25.smooth_75Bulk.bw
# 137-69_ChIP_qa-suz12_H3K27me3_Rep1_S66.bin_25.smooth_75Bulk.bw
# 137-70_ChIP_WT_H3K27me3_Rep1_S67.bin_25.smooth_75Bulk.bw
# 137-71_ChIP_qa-suz12_H3K27me3_Rep1_S68.bin_25.smooth_75Bulk.bw
# 137-72_ChIP_WT_H3K27me3_Rep1_S69.bin_25.smooth_75Bulk.bw
# 137-73_ChIP_qa-suz12_H3K27me3_Rep1_S70.bin_25.smooth_75Bulk.bw
# 137-74_ChIP_WT_H3K27me3_Rep1_S71.bin_25.smooth_75Bulk.bw
# 137-75_ChIP_qa-suz12_H3K27me3_Rep1_S72.bin_25.smooth_75Bulk.bw

#133-23_ChIP_WT_H3K9me3_Rep2.bin_25.smooth_75Bulk.bw
#133-24_ChIP_cac-1_H3K9me3_Rep2.bin_25.smooth_75Bulk.bw
#133-25_ChIP_cac-2_H3K9me3_Rep2.bin_25.smooth_75Bulk.bw

#129-90_ChIP_WT_H3K36me3_Rep1_S71_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#129-91_ChIP_cac-1_H3K36me3_Rep1_S72_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#129-92_ChIP_cac-2_H3K36me3_Rep1_S73_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#129-93_ChIP_cac-3_H3K36me3_Rep1_S74_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#129-94_ChIP_set-7_H3K36me3_Rep1_S75_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw

#138-62_ChIP_WT_H3K36me3_Rep2_6252_S61.bin_25.smooth_75Bulk.bw
#138-63_ChIP_cac-1_H3K36me3_Rep2_6252_S62.bin_25.smooth_75Bulk.bw
#138-64_ChIP_cac-2_H3K36me3_Rep2_6252_S63.bin_25.smooth_75Bulk.bw
#138-65_ChIP_cac-3_H3K36me3_Rep2_6252_S64.bin_25.smooth_75Bulk.bw
#138-66_ChIP_set-7_H3K36me3_Rep2_6252_S65.bin_25.smooth_75Bulk.bw

#124_1_ChIP_WT_K4me2_Rep1_4901.bin_25.smooth_50_BPM.bw
#124_2_ChIP_cac_1_K4me2_Rep1_4901.bin_25.smooth_50_BPM.bw
#124_3_ChIP_cac_2_K4me2_Rep1_4901.bin_25.smooth_50_BPM.bw
#124_4_ChIP_cac_3_K4me2_Rep1_4901.bin_25.smooth_50_BPM.bw
#124_5_ChIP_set_7_K4me2_Rep1_4901.bin_25.smooth_50_BPM.bw

#Run133
#133-5_ChIP_WT_H3K27me2me3_8hr_Rep1_S5.bin_25.smooth_75Bulk.bw
#133-6_ChIP_cac-1_H3K27me2me3_8hr_Rep1_S6.bin_25.smooth_75Bulk.bw
#133-7_ChIP_cac-2_H3K27me2me3_8hr_Rep1_S7.bin_25.smooth_75Bulk.bw
#133-8_ChIP_set-7_H3K27me2me3_8hr_Rep1_S8.bin_25.smooth_75Bulk.bw
#133-19_ChIP_WT_H4K20me3_Rep1.bin_25.smooth_75Bulk.bw
#133-20_ChIP_cac-1_H4K20me3_Rep1.bin_25.smooth_75Bulk.bw
#133-21_ChIP_cac-2_H4K20me3_Rep1.bin_25.smooth_75Bulk.bw
#133-22_ChIP_set-7_H4K20me3_Rep1.bin_25.smooth_75Bulk.bw

#131-22_ChIP_WT_H3K27me2me3_Rep1.bin_25.smooth_75Bulk.bw
#131-23_ChIP_cac-1_H3K27me2me3_Rep1.bin_25.smooth_75Bulk.bw
#131-24_ChIP_cac-2_H3K27me2me3_Rep1.bin_25.smooth_75Bulk.bw
#131-25_ChIP_cac-3_H3K27me2me3_Rep1.bin_25.smooth_75Bulk.bw
#131-26_ChIP_set-7_H3K27me2me3_Rep1.bin_25.smooth_75Bulk.bw

#131-82_ChIP_WT_H3K27me3_Rep1_S70_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#131-83_ChIP_cac-1_H3K27me3_Rep1_S71_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#131-84_ChIP_cac-2_H3K27me3_Rep1_S72_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#131-85_ChIP_cac-3_H3K27me3_Rep1_S73_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#131-86_ChIP_set-7_H3K27me3_Rep1_S74_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw

#129-38_ChIP_WT_K27me3_AbC_Rep_1_S37_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#129-39_ChIP_cac-1_K27me3_AbC_Rep_1_S38_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#129-40_ChIP_cac-2_K27me3_AbC_Rep_1_S39_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#129-41_ChIP_cac-3_K27me3_AbC_Rep_1_S40_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
#129-42_ChIP_set-7_K27me3_AbC_Rep_1_S41_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw

#Run 136
# 6147_136-10_ChIP_cac-1-2_H3K27me3_CS_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-11_ChIP_WT_input.bin_25.smooth_75Bulk.bw
# 6147_136-12_ChIP_cac-1_input.bin_25.smooth_75Bulk.bw
# 6147_136-13_ChIP_cac-2_input.bin_25.smooth_75Bulk.bw
# 6147_136-14_ChIP_cac-3_input.bin_25.smooth_75Bulk.bw
# 6147_136-1_ChIP_WT_H3K27me3_abcam_Rep2.bin_25.smooth_75Bulk.bw
# 6147_136-21_ChIP_cac-1-2_input.bin_25.smooth_75Bulk.bw
# 6147_136-22_ChIP_WT_H3K27me3_CS_0hr_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-23_ChIP_qa-suz12_H3K27me3_CS_0hr_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-24_ChIP_qa-suz12_cac-1_H3K27me3_CS_0hr_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-25_ChIP_WT_H3K27me3_CS_8hr_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-26_ChIP_qa-suz12_H3K27me3_CS_8hr_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-27_ChIP_qa-suz12_cac-1_H3K27me3_CS_8hr_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-28_ChIP_WT_H3K27me3_CS_24hr_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-29_ChIP_qa-suz12_H3K27me3_CS_24hr_Rep1.bin_25.smooth_75Bulk.bw
# 6147_136-2_ChIP_cac-1_H3K27me3_abcam_Rep2.bin_25.smooth_75Bulk.bw
# 6147_136-39_ChIP_qa-suz12_cac-1_H3K27me3_CS_24hr_Rep1_S39_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-3_ChIP_cac-2_H3K27me3_abcam_Rep2_S3_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-40_ChIP_WT_H3K27me3_abcam_6hr_Rep1_S40_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-41_ChIP_qa-suz12_H3K27me3_abcam_6hr_Rep1_S41_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-42_ChIP_qa-suz12_H3K27me3_abcam_6hr_Rep1_S42_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-43_ChIP_qa-suz12_cac-1_H3K27me3_abcam_6hr_Rep1_S43_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-44_ChIP_qa-suz12_cac-1_H3K27me3_abcam_6hr_Rep1_S44_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-45_ChIP_set-7_H3K27me3_abcam_6hr_Rep1_S45_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-4_ChIP_cac-3_H3K27me3_abcam_Rep2_S4_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-58_ChIP_WT_H3K27me3_abcam_Rep3_S58_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-5_ChIP_cac-1-2_H3K27me3_abcam_Rep2_S5_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-6_ChIP_WT_H3K27me3_CS_Rep1_S6_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-71_ChIP_cac-1_H3K27me3_abcam_Rep3_S70_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-72_ChIP_cac-2_H3K27me3_abcam_Rep3_S71_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-75_ChIP_cac-3_H3K27me3_abcam_Rep3_S74_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-76_ChIP_cac-1-2_H3K27me3_abcam_Rep3_S75_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-77_ChIP_set-7_H3K27me3_abcam_Rep3_S76_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-7_ChIP_cac-1_H3K27me3_CS_Rep1_S7_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-81_ChIP_cac-3_H3K27me3_CS_Rep2_S80_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-82_ChIP_cac-1-2_H3K27me3_CS_Rep2_S81_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-84_ChIP_WT_input_S83_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-85_ChIP_cac-1_input_S84_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-89_ChIP_cac-2_input_S88_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-8_ChIP_cac-2_H3K27me3_CS_Rep1_S8_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-91_ChIP_cac-1-2_input_S90_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-92_ChIP_set-7_input_S91_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw
# 6147_136-9_ChIP_cac-3_H3K27me3_CS_Rep1_S9_L001_R1_001_val_1.fq.gz.bin_25.smooth_75Bulk.bw

#Run 141
# 141-58_ChIP_WT_H3K23me1_Rep1_S52.bin_25.smooth_75Bulk.bw
# 141-59_ChIP_cac-1_H3K23me1_Rep1_S53.bin_25.smooth_75Bulk.bw
# 141-60_ChIP_cac-2_H3K23me1_Rep1_S54.bin_25.smooth_75Bulk.bw
# 141-61_ChIP_cac-3_H3K23me1_Rep1_S55.bin_25.smooth_75Bulk.bw
# 141-62_ChIP_set-7_H3K23me1_Rep1_S56.bin_25.smooth_75Bulk.bw
# 141-63_ChIP_WT_teto_P0_H3K27me3_Rep1_S57.bin_25.smooth_75Bulk.bw
# 141-64_ChIP_WT_teto_P1_H3K27me3_Rep1_S58.bin_25.smooth_75Bulk.bw
# 141-65_ChIP_WT_teto_P2_H3K27me3_Rep1_S59.bin_25.smooth_75Bulk.bw
# 141-66_ChIP_WT_teto_P3_H3K27me3_Rep1_S60.bin_25.smooth_75Bulk.bw
# 141-67_ChIP_cac-1_teto_P0_H3K27me3_Rep1_S61.bin_25.smooth_75Bulk.bw
# 141-68_ChIP_cac-1_teto_P1_H3K27me3_Rep1_S62.bin_25.smooth_75Bulk.bw
# 141-69_ChIP_cac-1_teto_P2_H3K27me3_Rep1_S63.bin_25.smooth_75Bulk.bw
# 141-70_ChIP_cac-1_teto_P3_H3K27me3_Rep1_S64.bin_25.smooth_75Bulk.bw
# 141-88_ChIP_WT_H3K27me2_Rep1_S82.bin_25.smooth_75Bulk.bw
# 141-89_ChIP_cac-1_H3K27me2_Rep1_S83.bin_25.smooth_75Bulk.bw
# 141-90_ChIP_cac-2_H3K27me2_Rep1_S84.bin_25.smooth_75Bulk.bw
# 141-91_ChIP_cac-3_H3K27me2_Rep1_S85.bin_25.smooth_75Bulk.bw
# 141-92_ChIP_set-7_H3K27me2_Rep1_S86.bin_25.smooth_75Bulk.bw
# 141-93_ChIP_WT_H4K12ac_Rep1_S87.bin_25.smooth_75Bulk.bw
# 141-94_ChIP_cac-1_H4K12ac_Rep1_S88.bin_25.smooth_75Bulk.bw
# 141-95_ChIP_cac-2_H4K12ac_Rep1_S89.bin_25.smooth_75Bulk.bw
# 141-96_ChIP_set-7_H4K12ac_Rep1_S90.bin_25.smooth_75Bulk.bw
# 141-N11_ATAC_WT__Rep1_S100.bin_25.smooth_75Bulk.bw
# 141-N12_ATAC_cac-1__Rep1_S101.bin_25.smooth_75Bulk.bw
# 141-N13_ATAC_cac-2__Rep1_S102.bin_25.smooth_75Bulk.bw
# 141-N14_ATAC_cac-3__Rep1_S103.bin_25.smooth_75Bulk.bw
# 141-N15_ATAC_set-7__Rep1_S104.bin_25.smooth_75Bulk.bw

#Run144
# 144-10_ChIP_tetO_p0_H3K27me3_Rep3_S10.bin_25.smooth_75Bulk.bw
# 144-11_ChIP_tetO_p1_H3K27me3_Rep3_S11.bin_25.smooth_75Bulk.bw
# 144-122_ChIP_tetO_p3_input__S122.bin_25.smooth_75Bulk.bw
# 144-124_ChIP_tetO_p1_input__S124.bin_25.smooth_75Bulk.bw
# 144-125_ChIP_tetO_p2_input__S125.bin_25.smooth_75Bulk.bw
# 144-126_ChIP_tetO_p3_input__S126.bin_25.smooth_75Bulk.bw
# 144-127_ChIP_tetO_p0_tet_input__S127.bin_25.smooth_75Bulk.bw
# 144-12_ChIP_tetO_p2_H3K27me3_Rep3_S12.bin_25.smooth_75Bulk.bw
# 144-132_ChIP_qa-suz12_Input__S132.bin_25.smooth_75Bulk.bw
# 144-13_ChIP_tetO_p3_H3K27me3_Rep3_S13.bin_25.smooth_75Bulk.bw
# 144-141_ChIP_qa-suz12_24hr_H3K27me2_Rep1_S141.bin_25.smooth_75Bulk.bw
# 144-14_ChIP_tetO_p0_H3K27me3_Rep4_S14.bin_25.smooth_75Bulk.bw
# 144-15_ChIP_tetO_p1_H3K27me3_Rep4_S15.bin_25.smooth_75Bulk.bw
# 144-16_ChIP_tetO_p2_H3K27me3_Rep4_S16.bin_25.smooth_75Bulk.bw
# 144-17_ChIP_tetO_p3_H3K27me3_Rep4_S17.bin_25.smooth_75Bulk.bw
# 144-18_ChIP_tetO_p0_H3K36me3_Rep1_S18.bin_25.smooth_75Bulk.bw
# 144-19_ChIP_tetO_p1_H3K36me3_Rep1_S19.bin_25.smooth_75Bulk.bw
# 144-1_ChIP_tetO_p0_H3K27me3_Rep2_S1.bin_25.smooth_75Bulk.bw
# 144-20_ChIP_tetO_p2_H3K36me3_Rep1_S20.bin_25.smooth_75Bulk.bw
# 144-21_ChIP_tetO_p3_H3K36me3_Rep1_S21.bin_25.smooth_75Bulk.bw
# 144-22_ChIP_tetO_p0_H3K36me3_Rep2_S22.bin_25.smooth_75Bulk.bw
# 144-23_ChIP_tetO_p1_H3K36me3_Rep2_S23.bin_25.smooth_75Bulk.bw
# 144-24_ChIP_tetO_p2_H3K36me3_Rep2_S24.bin_25.smooth_75Bulk.bw
# 144-25_ChIP_tetO_p3_H3K36me3_Rep2_S25.bin_25.smooth_75Bulk.bw
# 144-26_ChIP_tetO_p0_tet_H3K27me3_Rep2_S26.bin_25.smooth_75Bulk.bw
# 144-27_ChIP_tetO_p0_tet_H3K36me3_Rep2_S27.bin_25.smooth_75Bulk.bw
# 144-28_ChIP_WT_0hr_H3K27me3_Rep3_S28.bin_25.smooth_75Bulk.bw
# 144-29_ChIP_WT_24hr_H3K27me3_Rep2_S29.bin_25.smooth_75Bulk.bw
# 144-2_ChIP_tetO_p1_H3K27me3_Rep2_S2.bin_25.smooth_75Bulk.bw
# 144-30_ChIP_qa-suz12_0hr_H3K27me3_Rep3_S30.bin_25.smooth_75Bulk.bw
# 144-31_ChIP_qa-suz12_4hr_H3K27me3_Rep2_S31.bin_25.smooth_75Bulk.bw
# 144-32_ChIP_qa-suz12_8hr_H3K27me3_Rep2_S32.bin_25.smooth_75Bulk.bw
# 144-33_ChIP_qa-suz12_12hr_H3K27me3_Rep2_S33.bin_25.smooth_75Bulk.bw
# 144-34_ChIP_qa-suz12_24hr_H3K27me3_Rep3_S34.bin_25.smooth_75Bulk.bw
# 144-35_ChIP_qa-suz12_48hr_H3K27me3_Rep2_S35.bin_25.smooth_75Bulk.bw
# 144-37_ChIP_suz12_24hr_H3K27me3_Rep1_S37.bin_25.smooth_75Bulk.bw
# 144-38_ChIP_qa-suz12_cac-1_0hr_H3K27me3_Rep2_S38.bin_25.smooth_75Bulk.bw
# 144-39_ChIP_qa-suz12_cac-1_4hr_H3K27me3_Rep1_S39.bin_25.smooth_75Bulk.bw
# 144-3_ChIP_tetO_p2_H3K27me3_Rep2_S3.bin_25.smooth_75Bulk.bw
# 144-40_ChIP_qa-suz12_cac-1_8hr_H3K27me3_Rep1_S40.bin_25.smooth_75Bulk.bw
# 144-41_ChIP_qa-suz12_cac-1_12hr_H3K27me3_Rep2_S41.bin_25.smooth_75Bulk.bw
# 144-42_ChIP_qa-suz12_cac-1_24hr_H3K27me3_Rep2_S42.bin_25.smooth_75Bulk.bw
# 144-43_ChIP_qa-suz12_cac-1_48hr_H3K27me3_Rep2_S43.bin_25.smooth_75Bulk.bw
# 144-44_ChIP_WT_0hr_H3K27me3_Rep4_S44.bin_25.smooth_75Bulk.bw
# 144-45_ChIP_WT_24hr_H3K27me3_Rep3_S45.bin_25.smooth_75Bulk.bw
# 144-46_ChIP_suz12_0hr_H3K27me3_Rep2_S46.bin_25.smooth_75Bulk.bw
# 144-47_ChIP_suz12_24hr_H3K27me3_Rep2_S47.bin_25.smooth_75Bulk.bw
# 144-48_ChIP_qa-suz12_0hr_H3K27me3_Rep4_S48.bin_25.smooth_75Bulk.bw
# 144-49_ChIP_qa-suz12_4hr_H3K27me3_Rep3_S49.bin_25.smooth_75Bulk.bw
# 144-4_ChIP_tetO_p3_H3K27me3_Rep2_S4.bin_25.smooth_75Bulk.bw
# 144-50_ChIP_qa-suz12_8hr_H3K27me3_Rep3_S50.bin_25.smooth_75Bulk.bw
# 144-51_ChIP_qa-suz12_12hr_H3K27me3_Rep3_S51.bin_25.smooth_75Bulk.bw
# 144-52_ChIP_qa-suz12_24hr_H3K27me3_Rep4_S52.bin_25.smooth_75Bulk.bw
# 144-53_ChIP_WT_0hr_H3K27me2_Rep1_S53.bin_25.smooth_75Bulk.bw
# 144-54_ChIP_WT_24hr_H3K27me2_Rep1_S54.bin_25.smooth_75Bulk.bw
# 144-55_ChIP_suz12_0hr_H3K27me2_Rep1_S55.bin_25.smooth_75Bulk.bw
# 144-56_ChIP_suz12_24hr_H3K27me2_Rep1_S56.bin_25.smooth_75Bulk.bw
# 144-57_ChIP_qa-suz12_0hr_H3K27me2_Rep1_S57.bin_25.smooth_75Bulk.bw
# 144-58_ChIP_qa-suz12_4hr_H3K27me2_Rep1_S58.bin_25.smooth_75Bulk.bw
# 144-59_ChIP_qa-suz12_8hr_H3K27me2_Rep1_S59.bin_25.smooth_75Bulk.bw
# 144-5_ChIP_tetO_p0_tet_H3K27me3_Rep2_S5.bin_25.smooth_75Bulk.bw
# 144-60_ChIP_qa-suz12_12hr_H3K27me2_Rep1_S60.bin_25.smooth_75Bulk.bw
# 144-62_ChIP_WT_Input__S62.bin_25.smooth_75Bulk.bw
# 144-69_ChIP_suz12_Input__S69.bin_25.smooth_75Bulk.bw
# 144-6_ChIP_tetO_cac-1_p0_H3K27me3_Rep2_S6.bin_25.smooth_75Bulk.bw
# 144-71_ChIP_qa-suz12_Input__S71.bin_25.smooth_75Bulk.bw
# 144-73_ChIP_qa-suz12_Input__S73.bin_25.smooth_75Bulk.bw
# 144-79_ChIP_qa-suz12_Input__S79.bin_25.smooth_75Bulk.bw
# 144-7_ChIP_tetO_cac-1_p1_H3K27me3_Rep2_S7.bin_25.smooth_75Bulk.bw
# 144-8_ChIP_tetO_cac-1_p2_H3K27me3_Rep2_S8.bin_25.smooth_75Bulk.bw
# 144-9_ChIP_tetO_cac-1_p3_H3K27me3_Rep2_S9.bin_25.smooth_75Bulk.bw

#Run 146
# 146-106_ChIP_epr-1GFP_GFP-trap_Rep1_S125.bin_25.smooth_75Bulk.bw
# 146-10_ChIP_qa-suz12_72hr_H3K27me2_Rep1_S10.bin_25.smooth_75Bulk.bw
# 146-117_ChIP_qa-suz12_96hr_H3K27me2_Rep1_S136.bin_25.smooth_75Bulk.bw
# 146-118_ChIP_epr-1_GFP_H3K27me3_Rep1_S137.bin_25.smooth_75Bulk.bw
# 146-11_ChIP_qa-suz12_96hr_H3K27me2_Rep1_S11.bin_25.smooth_75Bulk.bw
# 146-123_ChIP_WT_H3K27me2_Rep1_S142.bin_25.smooth_75Bulk.bw
# 146-124_ChIP_suz12_0hr_H3K27me3_Rep1_S143.bin_25.smooth_75Bulk.bw
# 146-125_ChIP_qa-suz12_0hr_H3K27me3_Rep1_S144.bin_25.smooth_75Bulk.bw
# 146-126_ChIP_qa-suz12_4hr_H3K27me3_Rep1_S145.bin_25.smooth_75Bulk.bw
# 146-127_ChIP_qa-suz12_8hr_H3K27me3_Rep1_S146.bin_25.smooth_75Bulk.bw
# 146-128_ChIP_qa-suz12_12hr_H3K27me3_Rep1_S147.bin_25.smooth_75Bulk.bw
# 146-129_ChIP_qa-suz12_24hr_H3K27me3_Rep1_S148.bin_25.smooth_75Bulk.bw
# 146-12_ChIP_WT_H3K27me2_Rep1_S12.bin_25.smooth_75Bulk.bw
# 146-130_ChIP_suz12_0hr_H3K36me3_Rep1_S149.bin_25.smooth_75Bulk.bw
# 146-131_ChIP_qa-suz12_0hr_H3K36me3_Rep1_S150.bin_25.smooth_75Bulk.bw
# 146-132_ChIP_qa-suz12_4hr_H3K36me3_Rep1_S151.bin_25.smooth_75Bulk.bw
# 146-133_ChIP_qa-suz12_8hr_H3K36me3_Rep1_S152.bin_25.smooth_75Bulk.bw
# 146-134_ChIP_qa-suz12_12hr_H3K36me3_Rep1_S153.bin_25.smooth_75Bulk.bw
# 146-135_ChIP_qa-suz12_24hr_H3K36me3_Rep1_S154.bin_25.smooth_75Bulk.bw
# 146-136_ChIP_cac-2-epr-1-GFP_GFP-trap_Rep1_S155.bin_25.smooth_75Bulk.bw
# 146-137_ChIP_cac-2-epr-1-GFP_GFP-trap_Rep1_S156.bin_25.smooth_75Bulk.bw
# 146-13_ChIP_qa-suz12_0hr_input__S13.bin_25.smooth_75Bulk.bw
# 146-14_ChIP_qa-suz12_24hr_input__S14.bin_25.smooth_75Bulk.bw
# 146-15_ChIP_qa-suz12_48hr_input__S15.bin_25.smooth_75Bulk.bw
# 146-16_ChIP_qa-suz12_72hr_input__S16.bin_25.smooth_75Bulk.bw
# 146-17_ChIP_qa-suz12_96hr_input__S17.bin_25.smooth_75Bulk.bw
# 146-18_ChIP_WT_input__S18.bin_25.smooth_75Bulk.bw
# 146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw
# 146-1_ChIP_qa-suz12_0hr_H3K27me3_Rep4_S1.bin_25.smooth_75Bulk.bw
# 146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw
# 146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw
# 146-22_ChIP_cac-3_H3K4me2_Rep1_S22.bin_25.smooth_75Bulk.bw
# 146-23_ChIP_set-7_H3K4me2_Rep1_S23.bin_25.smooth_75Bulk.bw
# 146-24_ChIP_WT_H3K27me2_Rep2_S24.bin_25.smooth_75Bulk.bw
# 146-25_ChIP_cac-1_H3K27me2_Rep2_S25.bin_25.smooth_75Bulk.bw
# 146-26_ChIP_cac-2_H3K27me2_Rep2_S26.bin_25.smooth_75Bulk.bw
# 146-27_ChIP_cac-3_H3K27me2_Rep2_S27.bin_25.smooth_75Bulk.bw
# 146-28_ChIP_set-7_H3K27me2_Rep2_S28.bin_25.smooth_75Bulk.bw
# 146-29_ChIP_WT_H3K4me2_Rep2_S29.bin_25.smooth_75Bulk.bw
# 146-2_ChIP_qa-suz12_24hr_H3K27me3_Rep4_S2.bin_25.smooth_75Bulk.bw
# 146-30_ChIP_cac-1_H3K4me2_Rep2_S30.bin_25.smooth_75Bulk.bw
# 146-31_ChIP_cac-2_H3K4me2_Rep2_S31.bin_25.smooth_75Bulk.bw
# 146-32_ChIP_cac-3_H3K4me2_Rep2_S32.bin_25.smooth_75Bulk.bw
# 146-33_ChIP_set-7_H3K4me2_Rep2_S33.bin_25.smooth_75Bulk.bw
# 146-34_ChIP_WT_input__S34.bin_25.smooth_75Bulk.bw
# 146-35_ChIP_cac-1_input__S35.bin_25.smooth_75Bulk.bw
# 146-36_ChIP_cac-2_input__S36.bin_25.smooth_75Bulk.bw
# 146-37_ChIP_cac-3_input__S37.bin_25.smooth_75Bulk.bw
# 146-38_ChIP_set-7_input__S38.bin_25.smooth_75Bulk.bw
# 146-39_ChIP_qa-suz12_0hr_H3K27me3_Rep1_S39.bin_25.smooth_75Bulk.bw
# 146-3_ChIP_qa-suz12_48hr_H3K27me3_Rep1_S3.bin_25.smooth_75Bulk.bw
# 146-40_ChIP_qa-suz12_24hr_H3K27me3_Rep1_S40.bin_25.smooth_75Bulk.bw
# 146-41_ChIP_qa-suz12_48hr_H3K27me3_Rep1_S41.bin_25.smooth_75Bulk.bw
# 146-42_ChIP_qa-suz12_72hr_H3K27me3_Rep1_S42.bin_25.smooth_75Bulk.bw
# 146-43_ChIP_qa-suz12_96hr_H3K27me3_Rep1_S43.bin_25.smooth_75Bulk.bw
# 146-44_ChIP_WT_H3K27me3_Rep1_S44.bin_25.smooth_75Bulk.bw
# 146-45_ChIP_qa-suz12_0hr_H3K27me2_Rep1_S45.bin_25.smooth_75Bulk.bw
# 146-46_ChIP_qa-suz12_24hr_H3K27me2_Rep1_S46.bin_25.smooth_75Bulk.bw
# 146-47_ChIP_qa-suz12_48hr_H3K27me2_Rep1_S47.bin_25.smooth_75Bulk.bw
# 146-48_ChIP_qa-suz12_72hr_H3K27me2_Rep1_S48.bin_25.smooth_75Bulk.bw
# 146-4_ChIP_qa-suz12_72hr_H3K27me3_Rep1_S4.bin_25.smooth_75Bulk.bw
# 146-50_ChIP_tet_R_SUZ12_H3K27me3__S50.bin_25.smooth_75Bulk.bw
# 146-51_ChIP_tet_R_SUZ12_H3K27me3__S51.bin_25.smooth_75Bulk.bw
# 146-52_ChIP_tet_R_SUZ12_H3K27me3__S52.bin_25.smooth_75Bulk.bw
# 146-53_ChIP_tet_R_SUZ12_H3K27me3__S53.bin_25.smooth_75Bulk.bw
# 146-54_ChIP_tet_R_SUZ12_H3K27me3__S54.bin_25.smooth_75Bulk.bw
# 146-55_ChIP_tet_R_SUZ12_H3K27me3__S55.bin_25.smooth_75Bulk.bw
# 146-56_ChIP_tet_R_SUZ12_iswi_mut_H3K27me3__S56.bin_25.smooth_75Bulk.bw
# 146-57_ChIP_tet_R_SUZ12_iswi_mut_H3K27me3__S57.bin_25.smooth_75Bulk.bw
# 146-58_ChIP_tet_R_SUZ12_iswi_mut_H3K27me3__S58.bin_25.smooth_75Bulk.bw
# 146-59_ChIP_tet_R_SUZ12_iswi_mut_H3K27me3__S59.bin_25.smooth_75Bulk.bw
# 146-5_ChIP_qa-suz12_96hr_H3K27me3_Rep1_S5.bin_25.smooth_75Bulk.bw
# 146-60_ChIP_tet_R_SUZ12_iswi_mut_H3K27me3__S60.bin_25.smooth_75Bulk.bw
# 146-61_ChIP_tet_R_SUZ12_iswi_mut_H3K27me3__S61.bin_25.smooth_75Bulk.bw
# 146-6_ChIP_WT_H3K27me3_Rep1_S6.bin_25.smooth_75Bulk.bw
# 146-7_ChIP_qa-suz12_0hr_H3K27me2_Rep1_S7.bin_25.smooth_75Bulk.bw
# 146-8_ChIP_qa-suz12_24hr_H3K27me2_Rep1_S8.bin_25.smooth_75Bulk.bw
# 146-9_ChIP_qa-suz12_48hr_H3K27me2_Rep1_S9.bin_25.smooth_75Bulk.bw
# 146-N1_ATAC_WT__Rep2_S97.bin_25.smooth_75Bulk.bw
# 146-N3_ATAC_cac-1__Rep2_S98.bin_25.smooth_75Bulk.bw
# 146-N4_ATAC_cac-2__Rep2_S99.bin_25.smooth_75Bulk.bw
# 146-N5_ATAC_set-7__Rep2_S100.bin_25.smooth_75Bulk.bw
# 146-N6_ATAC_cac-3__Rep2_S101.bin_25.smooth_75Bulk.bw

#Run 149
# 149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw
# 149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw
# 149-102_ChIP_cac-3_H3K36me3_Rep3_S126.bin_25.smooth_75Bulk.bw
# 149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw
# 149-104_ChIP_WT_H3K9me3_Rep3_S128.bin_25.smooth_75Bulk.bw
# 149-105_ChIP_cac-1_H3K9me3_Rep3_S129.bin_25.smooth_75Bulk.bw
# 149-106_ChIP_cac-2_H3K9me3_Rep3_S130.bin_25.smooth_75Bulk.bw
# 149-107_ChIP_cac-3_H3K9me3_Rep3_S131.bin_25.smooth_75Bulk.bw
# 149-108_ChIP_set-7_Input_Rep3_S132.bin_25.smooth_75Bulk.bw
# 149-122_ChIP_cac-2_comp_H3K27me3_Rep1_S146.bin_25.smooth_75Bulk.bw
# 149-123_ChIP_cac-2_comp_H3K27me3_Rep1_S147.bin_25.smooth_75Bulk.bw
# 149-128_ChIP_cac-2_comp_H3K4me2_Rep1_S152.bin_25.smooth_75Bulk.bw
# 149-129_ChIP_cac-2_comp_H3K4me2_Rep1_S153.bin_25.smooth_75Bulk.bw
# 149-130_ChIP_cac-2_comp_input__S154.bin_25.smooth_75Bulk.bw
# 149-131_ChIP_cac-2_comp_input__S155.bin_25.smooth_75Bulk.bw
# 149-134_ChIP_WT_input__S158.bin_25.smooth_75Bulk.bw
# 149-135_ChIP_cac-1_input__S159.bin_25.smooth_75Bulk.bw
# 149-136_ChIP_cac-2_input__S160.bin_25.smooth_75Bulk.bw
# 149-137_ChIP_cac-3_input__S161.bin_25.smooth_75Bulk.bw
# 149-138_ChIP_set-7_input__S162.bin_25.smooth_75Bulk.bw
# 149-55_ChIP_WT_H3K27me3__S55.bin_25.smooth_75Bulk.bw
# 149-56_ChIP_cac-1_H3K27me3__S56.bin_25.smooth_75Bulk.bw
# 149-57_ChIP_rtt106_H3K27me3_Rep1_S57.bin_25.smooth_75Bulk.bw
# 149-58_ChIP_cac-1-rtt106_H3K27me3_Rep1_S58.bin_25.smooth_75Bulk.bw
# 149-59_ChIP_WT_H3K4me2__S59.bin_25.smooth_75Bulk.bw
# 149-60_ChIP_cac-1_H3K4me2__S60.bin_25.smooth_75Bulk.bw
# 149-61_ChIP_rtt106_H3K4me2_Rep1_S61.bin_25.smooth_75Bulk.bw
# 149-62_ChIP_cac-1-rtt106_H3K4me2_Rep1_S62.bin_25.smooth_75Bulk.bw
# 149-63_ChIP_WT_H3K27me3__S63.bin_25.smooth_75Bulk.bw
# 149-64_ChIP_cac-1_H3K27me3__S64.bin_25.smooth_75Bulk.bw
# 149-68_ChIP_rtt106_H3K27me3_Rep2_S68.bin_25.smooth_75Bulk.bw
# 149-69_ChIP_cac-1-rtt106_H3K27me3_Rep2_S69.bin_25.smooth_75Bulk.bw
# 149-70_ChIP_WT_H3K4me2__S70.bin_25.smooth_75Bulk.bw
# 149-71_ChIP_cac-1_H3K4me2__S71.bin_25.smooth_75Bulk.bw
# 149-72_ChIP_rtt106_H3K4me2_Rep2_S72.bin_25.smooth_75Bulk.bw
# 149-73_ChIP_cac-1-rtt106_H3K4me2_Rep2_S73.bin_25.smooth_75Bulk.bw
# 149-74_ChIP_WT_H4K16ac_Rep1_S74.bin_25.smooth_75Bulk.bw
# 149-75_ChIP_cac-1_H4K16ac_Rep1_S75.bin_25.smooth_75Bulk.bw
# 149-76_ChIP_cac-2_H4K16ac_Rep1_S76.bin_25.smooth_75Bulk.bw
# 149-77_ChIP_cac-3_H4K16ac_Rep1_S77.bin_25.smooth_75Bulk.bw
# 149-78_ChIP_set-7_H4K16ac_Rep1_S78.bin_25.smooth_75Bulk.bw
# 149-79_ChIP_WT_H3K27ac_Rep2_S79.bin_25.smooth_75Bulk.bw
# 149-80_ChIP_cac-1_H3K27ac_Rep2_S80.bin_25.smooth_75Bulk.bw
# 149-81_ChIP_cac-2_H3K27ac_Rep2_S81.bin_25.smooth_75Bulk.bw
# 149-82_ChIP_cac-3_H3K27ac_Rep2_S82.bin_25.smooth_75Bulk.bw
# 149-83_ChIP_set-7_H3K27ac_Rep2_S83.bin_25.smooth_75Bulk.bw
# 149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw

#Run 1250150-100_ChIP_cac-3_input__S115.bin_25.smooth_75Bulk.bw
# 150-116_ChIP_cac-2_H3K36me3_Rep4_S131.bin_25.smooth_75Bulk.bw
# 150-131_ChIP_cac-3_H3K36me3_Rep4_S146.bin_25.smooth_75Bulk.bw
# 150-134_ChIP_set-7_H3K36me3_Rep4_S149.bin_25.smooth_75Bulk.bw
# 150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw
# 150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw
# 150-137_ChIP_cac-2_Kac_Rep2_S152.bin_25.smooth_75Bulk.bw
# 150-138_ChIP_cac-3_Kac_Rep2_S153.bin_25.smooth_75Bulk.bw
# 150-139_ChIP_set-7_Kac_Rep2_S154.bin_25.smooth_75Bulk.bw
# 150-93_ChIP_WT_H3K36me3_Rep4_S93.bin_25.smooth_75Bulk.bw
# 150-94_ChIP_cac-1_H3K36me3_Rep4_S94.bin_25.smooth_75Bulk.bw
# 150-97_ChIP_WT_input__S112.bin_25.smooth_75Bulk.bw
# 150-98_ChIP_cac-1_input__S113.bin_25.smooth_75Bulk.bw
# 150-99_ChIP_cac-2_input__S114.bin_25.smooth_75Bulk.bw
