#!/bin/bash
#SBATCH --job-name=CAF1_Paper_Heatmap
#SBATCH --partition=batch
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=evt82290@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=50gb
#SBATCH --time=6:00:00
#SBATCH --output=../Heatmap/logs/CAFHeatmap.%j.out
#SBATCH --error=../Heatmap/logs/CAFHeatmap.%j.err

#output directories
OUTDIR1="/scratch/evt82290/Heatmaps/qa-suz12"
OUTDIR2="/scratch/evt82290/RNAseq/misc_mutants/bigWig"
OUTDIR3="/scratch/evt82290/MappingOutputs/RNAseq_split/bigWig"

#bigWig directories
P126DIR="/scratch/evt82290/MappingOutputs/Run126/bigWig"
P129DIR="/scratch/evt82290/MappingOutputs/Run129/bigWig"
P131DIR="/scratch/evt82290/MappingOutputs/Run131/bigWig"
P133DIR="/scratch/evt82290/MappingOutputs/Run133/bigWig"
P136DIR="/scratch/evt82290/MappingOutputs/Run136/bigWig"
P137DIR="/scratch/evt82290/MappingOutputs/Run137/bigWig"
P138DIR="/scratch/evt82290/MappingOutputs/Run138/bigWig"
P139DIR="/scratch/evt82290/MappingOutputs/Run139/bigWig"
P141DIR="/scratch/evt82290/MappingOutputs/Run141/bigWig"
P144DIR="/scratch/evt82290/MappingOutputs/Run144/bigWig"
P145DIR="/scratch/evt82290/MappingOutputs/Run145/bigWig"
P146DIR="/scratch/evt82290/MappingOutputs/Run146/bigWig"
P148DIR="/scratch/evt82290/MappingOutputs/Run148/bigWig"
P149DIR="/scratch/evt82290/MappingOutputs/Run149/bigWig"
P150DIR="/scratch/evt82290/MappingOutputs/Run150/bigWig"
P151DIR="/scratch/evt82290/MappingOutputs/Run151/bigWig"
P152DIR="/scratch/evt82290/MappingOutputs/Run152/bigWig"
MISCDIR="/scratch/evt82290/MappingOutputs/misc_data/bigWig"
RNADIR="/scratch/evt82290/MappingOutputs/RNAseq/bigWig"
ATACDIR="/scratch/evt82290/MappingOutputs/ATAC/BigWigs"

#bed file directories
QABED="/home/evt82290/Research/bed_files/qa-suz12"
BEDDIR="/scratch/evt82290/RNAseqIGV/bedgraph"
BEDDIR2="/home/evt82290/Research/bed_files"

#load deeptools
module load deepTools

###Figure 3
###K27 genes
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/H3K27me3_methylated_TSS_Promoters_FINAL.bed --missingDataAsZero --skipZeros -o K36_matrix_PRC2.gz
#
#     plotHeatmap -m K36_matrix_PRC2.gz -out CAF-1_H3K36me3_K27genes.pdf \
#                     --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --outFileSortedRegions CAF-1_K36_order_K27genes.bed \
#                     --sortUsingSamples 1 3 4 \
#                     --heatmapHeight 25 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# ###ASH-1 methylated
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/ash1_meth_nonK27.bed --missingDataAsZero --skipZeros -o K36_matrix_ash1.gz
#
#     plotHeatmap -m K36_matrix_ash1.gz -out CAF-1_H3K36me3_ash1_methylated_nonK27_genes.pdf \
#                     --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 3 4 \
#                     --heatmapHeight 25 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12

###SET-2 methylated
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/set2_meth_only.bed --missingDataAsZero --skipZeros -o K36_matrix_set2.gz
#
#     plotHeatmap -m K36_matrix_set2.gz -out CAF-1_H3K36me3_set_methylated_only_genes.pdf \
#                     --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 3 4 \
#                     --heatmapHeight 25 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12

#TEST
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF-1_K36retain.bed --missingDataAsZero --skipZeros -o K36_test.gz
#
#     plotHeatmap -m K36_test.gz -out K36_cluster_test.pdf \
#                     --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 3 4 \
#                     --heatmapHeight 25 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#   -R $BEDDIR2/CAF-1_K27lost.bed $BEDDIR2/CAF-1_K27retain.bed --missingDataAsZero --skipZeros -o K27_test.gz
#
# plotHeatmap -m K27_test.gz -out K27_cluster_test.pdf \
#                     --samplesLabel WT cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 2 3 \
#                     --heatmapHeight 25 \
#                     --colorList 'white,g,darkgreen' \
#                     --zMin 0 --zMax 50
#
# ###Figure 4
# ###cluster of K27 & K36 lost genes
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $MISCDIR/ash1_H3K27me2me3_Rep2.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF1_K27_lost_only.bed $BEDDIR2/CAF1_K36_K27_retain.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_K27_clustered_K27order.pdf \
#                     --samplesLabel WT cac-1 ash-1 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 2 \
#                     --heatmapHeight 24 \
#                     --outFileSortedRegions K27_order.bed \
#                     --legendLocation none \
#                     --colorList 'white,g,darkgreen' \
#                     --zMin 0 --zMax 50
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF1_K27_lost_only.bed $BEDDIR2/CAF1_K36_K27_retain.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_K36_clustered_K27order.pdf \
#                     --samplesLabel WT cac-1 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --heatmapHeight 24 \
#                     --outFileSortedRegions K36_order.bed \
#                     --legendLocation none \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# ##applying to H3K4me2 & Kac
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-23_ChIP_set-7_H3K4me2_Rep1_S23.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF1_K27_lost_only.bed $BEDDIR2/CAF1_K36_K27_retain.bed \
#   --skipZeros --missingDataAsZero -o matrix_CAF-1_K4_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_K4_clustered.gz -out H3K27me3_CAF-1_K4_clustered_K27order.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "TSS" \
#   --sortRegions descend \
#   --outFileSortedRegions K4_order.bed \
#   --heatmapHeight 24 \
#   --colorList 'white,magenta' \
#   --zMin 0
#
# ###Kac
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P150DIR/150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-137_ChIP_cac-2_Kac_Rep2_S152.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-139_ChIP_set-7_Kac_Rep2_S154.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF1_K27_lost_only.bed $BEDDIR2/CAF1_K36_K27_retain.bed \
#   --skipZeros --missingDataAsZero -o matrix_CAF-1_Kac_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_Kac_clustered.gz -out H3K27me3_CAF-1_Kac_clustered_K27order.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "TSS" \
#   --sortRegions descend \
#   --heatmapHeight 24 \
#   --outFileSortedRegions Kac_order.bed \
#   --colorList 'white, lavender, mediumslateblue' \
#   --zMin 0 --zMax 8
#
# ##All_combined
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-23_ChIP_set-7_H3K4me2_Rep1_S23.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-137_ChIP_cac-2_Kac_Rep2_S152.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-139_ChIP_set-7_Kac_Rep2_S154.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/K27_order.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_allmods_clustered_K27order.pdf \
#                     --samplesLabel WT cac-1 WT cac-1 WT cac-1 cac-2 set-7 WT cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions no \
#                     --heatmapHeight 24 \
#                     --whatToShow "heatmap and colorbar" \
#                     --legendLocation none \
#                     --colorList 'white,g,darkgreen' 'white,g,darkgreen' 'yellow, orange, brown' 'yellow, orange, brown' 'white,magenta' 'white,magenta' 'white,magenta' 'white,magenta' 'white, lavender, mediumslateblue' 'white, lavender, mediumslateblue' 'white, lavender, mediumslateblue' 'white, lavender, mediumslateblue' \
#                     --zMin 0 --zMax 50 50 12 12 5 5 5 5 8 8 8 8


# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $MISCDIR/ash1_H3K27me2me3_Rep2.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF1_K27_lost_only.bed $BEDDIR2/CAF1_K36_K27_retain.bed \
#    --missingDataAsZero --skipZeros -o K27_test.gz
#
# plotHeatmap -m K27_test.gz -out K27_genes_ASH1_K27_clustered.pdf \
#                     --samplesLabel WT cac-1 ash-1 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --heatmapHeight 24 \
#                     --outFileSortedRegions $BEDDIR2/ASH1_K27_order.bed \
#                     --legendLocation none \
#                     --colorList 'white,g,darkgreen' \
#                     --zMin 0 --zMax 50
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/ASH1_K27_order.bed \
#    --missingDataAsZero --skipZeros -o K36_test.gz
#
# plotHeatmap -m K36_test.gz -out K27_genes_ASH1_K36_clustered.pdf \
#                     --samplesLabel WT cac-1 ash-1 \
#                     --startLabel "TSS" \
#                     --sortRegions no \
#                     --heatmapHeight 24 \
#                     --legendLocation none \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12

# #RNA-seq
computeMatrix scale-regions -a 200 -b 200 --regionBodyLength 2000 --scale 2 \
      -S $RNADIR/SRR8269825/SRR8269825_log.bw \
         /scratch/evt82290/MappingOutputs/Run149/RNA/bigWig/149-115_RNA_cac-1__Rep1_S139/149-115_RNA_cac-1__Rep1_S139_log.bw \
         $RNADIR/SRR7690268/SRR7690268_log.bw \
         $RNADIR/SRR10916163/SRR10916163_log.bw \
         -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF1_K27_lost_only.bed $BEDDIR2/CAF1_K36_K27_retain.bed --skipZeros --missingDataAsZero -o matrix_PRC2_RNA.gz

    plotHeatmap -m matrix_PRC2_RNA.gz -out CAF-1_ash1_RNA-seq_K27genes_CAF-1_clustered.pdf \
            --samplesLabel WT cac-1 ash-1 set-7 \
            --startLabel "TSS" \
            --endLabel "TES" \
            --sortRegions descend \
            --sortUsingSamples 2 3 4 \
            --outFileSortedRegions $BEDDIR2/K27genes_lost_RNA_order.bed \
            --heatmapHeight 24 \
            --legendLocation none \
            --colorMap "bwr" \
            --zMin 0 --zMax 3

         # $OUTDIR2/SRR10916163_log.bw \

# CAF-1_K27lost.bed
# CAF-1_K27retain.bed


#ChatGPT method
############################
# 1) TSS-centered panel
############################
#!/usr/bin/env bash
# Build each matrix & PDF separately (preserving YOUR plot settings),
# then stitch side-by-side with ImageMagick in the order: K27 | K36 | Kac | K4.

# set -euo pipefail
#
# if command -v module >/dev/null 2>&1; then
#   module load ImageMagick || true
# fi
#
#
# #######################################
# #1) K27 (TSS-centered) -> defines row order
# #######################################
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#   -S \
#     "$P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw" \
#     "$P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw" \
#   -R \
#     "$BEDDIR2/CAF-1_K36lost.bed" \
#     "$BEDDIR2/CAF1_K27_lost_only.bed" \
#     "$BEDDIR2/CAF1_K36_K27_retain.bed" \
#   --missingDataAsZero --skipZeros \
#   -o matrix_K27.mat.gz
#
# plotHeatmap -m matrix_K27.mat.gz \
#   -out K27_genes_CAF-1_K27_clustered_K27order.pdf \
#   --samplesLabel WT cac-1 \
#   --startLabel "TSS" \
#   --sortRegions descend \
#   --sortUsingSamples 1 2 \
#   --heatmapHeight 24 \
#   --outFileSortedRegions "$BEDDIR2/K27_order.bed" \
#   --legendLocation none \
#   --colorList 'white,g,darkgreen' \
#   --zMin 0 --zMax 50
#
# ########################################
# # 2) K36 (TSS-centered) using K27 row order
# ########################################
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#   -S \
#     "$P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw" \
#     "$P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw" \
#   -R "$BEDDIR2/K27_order.bed" \
#   --missingDataAsZero --skipZeros \
#   -o matrix_K36.mat.gz
#
# plotHeatmap -m matrix_K36.mat.gz \
#   -out K27_genes_CAF-1_K36_clustered_K27order.pdf \
#   --samplesLabel WT cac-1 \
#   --startLabel "TSS" \
#   --sortRegions no \
#   --heatmapHeight 24 \
#   --legendLocation none \
#   --colorMap "afmhot_r" \
#   --zMin 0 --zMax 12
#
# ########################################
# # 3) Kac (TSS-centered) using K27 row order
# ########################################
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#   -S \
#     "$P150DIR/150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw" \
#     "$P150DIR/150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw" \
#     "$P150DIR/150-137_ChIP_cac-2_Kac_Rep2_S152.bin_25.smooth_75Bulk.bw" \
#     "$P150DIR/150-139_ChIP_set-7_Kac_Rep2_S154.bin_25.smooth_75Bulk.bw" \
#   -R "$BEDDIR2/K27_order.bed" \
#   --missingDataAsZero --skipZeros \
#   -o matrix_Kac.mat.gz
#
# plotHeatmap -m matrix_Kac.mat.gz \
#   -out H3K27me3_CAF-1_Kac_clustered_K27order.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "TSS" \
#   --sortRegions no \
#   --heatmapHeight 24 \
#   --legendLocation none \
#   --colorList 'white, lavender, mediumslateblue' \
#   --zMin 0 --zMax 8
#
# ########################################
# # 4) K4 (GENE BODIES via scale-regions) using K27 row order
# ########################################
# computeMatrix scale-regions \
#   -S \
#     "$P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw" \
#     "$P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw" \
#     "$P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw" \
#     "$P146DIR/146-23_ChIP_set-7_H3K4me2_Rep1_S23.bin_25.smooth_75Bulk.bw" \
#   -R "$BEDDIR2/K27_order.bed" \
#   --missingDataAsZero --skipZeros \
#   -o matrix_K4_scale.mat.gz
#
# plotHeatmap -m matrix_K4_scale.mat.gz \
#   -out H3K27me3_CAF-1_K4_clustered_K27order.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "TSS" --endLabel "TES" \
#   --sortRegions no \
#   --heatmapHeight 24 \
#   --legendLocation none \
#   --colorList 'white, magenta' \
#   --zMin 0
