#!/bin/bash
#SBATCH --job-name=CAF1_Paper_Heatmap
#SBATCH --partition=batch
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=evt82290@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=50gb
#SBATCH --time=6:00:00
#SBATCH --output=../Heatmap/logs/CAFHeatmap.%j.out
#SBATCH --error=../Heatmap/logs/CAFHeatmap.%j.err

#output directories
OUTDIR1="/scratch/evt82290/Heatmaps/qa-suz12"
OUTDIR2="/scratch/evt82290/RNAseq/misc_mutants/bigWig"
OUTDIR3="/scratch/evt82290/MappingOutputs/RNAseq_split/bigWig"

#bigWig directories
P126DIR="/scratch/evt82290/MappingOutputs/Run126/bigWig"
P129DIR="/scratch/evt82290/MappingOutputs/Run129/bigWig"
P131DIR="/scratch/evt82290/MappingOutputs/Run131/bigWig"
P133DIR="/scratch/evt82290/MappingOutputs/Run133/bigWig"
P136DIR="/scratch/evt82290/MappingOutputs/Run136/bigWig"
P137DIR="/scratch/evt82290/MappingOutputs/Run137/bigWig"
P138DIR="/scratch/evt82290/MappingOutputs/Run138/bigWig"
P139DIR="/scratch/evt82290/MappingOutputs/Run139/bigWig"
P141DIR="/scratch/evt82290/MappingOutputs/Run141/bigWig"
P144DIR="/scratch/evt82290/MappingOutputs/Run144/bigWig"
P145DIR="/scratch/evt82290/MappingOutputs/Run145/bigWig"
P146DIR="/scratch/evt82290/MappingOutputs/Run146/bigWig"
P148DIR="/scratch/evt82290/MappingOutputs/Run148/bigWig"
P149DIR="/scratch/evt82290/MappingOutputs/Run149/bigWig"
P150DIR="/scratch/evt82290/MappingOutputs/Run150/bigWig"
P151DIR="/scratch/evt82290/MappingOutputs/Run151/bigWig"
P152DIR="/scratch/evt82290/MappingOutputs/Run152/bigWig"
MISCDIR="/scratch/evt82290/MappingOutputs/misc_data/bigWig"
RNADIR="/scratch/evt82290/MappingOutputs/RNAseq/bigWig"
ATACDIR="/scratch/evt82290/MappingOutputs/ATAC/BigWigs"

#bed file directories
QABED="/home/evt82290/Research/bed_files/qa-suz12"
BEDDIR="/scratch/evt82290/RNAseqIGV/bedgraph"
BEDDIR2="/home/evt82290/Research/bed_files"

#load deeptools
module load deepTools

###Figure 3
###K27 genes
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/K27genes_K36enriched.bed --missingDataAsZero --skipZeros -o K36_matrix_PRC2.gz
#
#     plotHeatmap -m K36_matrix_PRC2.gz -out CAF-1_H3K36me3_K27genes.pdf \
#                     --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --legendLocation none \
#                     --outFileSortedRegions CAF-1_K36_order_K27genes.bed \
#                     --sortUsingSamples 1 3 4 \
#                     --heatmapHeight 25 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12

# ###ASH-1 methylated
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/ash1_meth_nonK27.bed --missingDataAsZero --skipZeros -o K36_matrix_ash1.gz
#
#     plotHeatmap -m K36_matrix_ash1.gz -out CAF-1_H3K36me3_ash1_methylated_nonK27_genes.pdf \
#                     --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 3 4 \
#                     --heatmapHeight 25 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# ##SET-2 methylated
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/set2_meth_only.bed --missingDataAsZero --skipZeros -o K36_matrix_set2.gz
#
#     plotHeatmap -m K36_matrix_set2.gz -out CAF-1_H3K36me3_set_methylated_only_genes.pdf \
#                     --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 3 4 \
#                     --heatmapHeight 25 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12

#Clustering
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-103_ChIP_set-7_H3K36me3_Rep3_S127.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF-1_K36retain.bed --missingDataAsZero --skipZeros -o K36_test.gz
#
#     plotHeatmap -m K36_test.gz -out K36_cluster_test.pdf \
#                     --samplesLabel WT ash-1 cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --legendLocation none \
#                     --sortUsingSamples 1 3 4 \
#                     --whatToShow "heatmap and colorbar" \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# # computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-83_ChIP_set-7_H3K27me3_CS_Rep2_S82.bin_25.smooth_75Bulk.bw \
#   -R $BEDDIR2/CAF-1_K27lost.bed $BEDDIR2/CAF-1_K27retain.bed --missingDataAsZero --skipZeros -o K27_test.gz
#
# plotHeatmap -m K27_test.gz -out K27_cluster_test.pdf \
#                     --samplesLabel WT cac-1 cac-2 set-7 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 2 3 \
#                     --heatmapHeight 25 \
#                     --colorList 'white,g,darkgreen' \
#                     --zMin 0 --zMax 50
# #
# ###Figure 4


###############################
###TESTING

###Kac
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P150DIR/150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-137_ChIP_cac-2_Kac_Rep2_S152.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-139_ChIP_set-7_Kac_Rep2_S154.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/Kac_Gain_CAF1.bed $BEDDIR2/Kac_Gain_set7.bed $BEDDIR2/Kac_no_change.bed \
#   --skipZeros --missingDataAsZero -o matrix_CAF-1_Kac_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_Kac_clustered.gz -out H3K27me3_CAF-1_Kac_clustered_Kaccluster.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "TSS" \
#   --sortRegions descend \
#   --heatmapHeight 24 \
#   --legendLocation none \
#   --outFileSortedRegions $BEDDIR2/Kac_cluster_order.bed \
#   --colorList 'white, lavender, mediumslateblue' \
#   --zMin 0 --zMax 8
#
# ###K4
# computeMatrix scale-regions \
# -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-23_ChIP_set-7_H3K4me2_Rep1_S23.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/K4_Gain_CAF1.bed $BEDDIR2/K4_Gain_set7.bed $BEDDIR2/K4_no_change.bed \
#   --skipZeros --missingDataAsZero -o matrix_CAF-1_K4_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_K4_clustered.gz -out H3K27me3_CAF-1_K4_clustered_K4cluster.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "TSS" --endLabel "TES" \
#   --sortRegions descend \
#   --heatmapHeight 24 \
#   --legendLocation none \
#   --outFileSortedRegions $BEDDIR2/K4_cluster_order.bed \
#   --colorList 'white, magenta' \
#   --zMin 0
#
# ###K27 & K36
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $MISCDIR/ash1_H3K27me2me3_Rep2.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/Kac_cluster_order.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_K27_Kacorder.pdf \
#                     --samplesLabel WT cac-1 ash-1 \
#                     --startLabel "TSS" \
#                     --sortRegions no \
#                     --heatmapHeight 24 \
#                     --legendLocation none \
#                     --colorList 'white,g,darkgreen' \
#                     --zMin 0 --zMax 50
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $MISCDIR/ash1_H3K27me2me3_Rep2.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/K4_cluster_order.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_K27_K4order.pdf \
#                     --samplesLabel WT cac-1 ash-1 \
#                     --startLabel "TSS" \
#                     --sortRegions no \
#                     --heatmapHeight 24 \
#                     --legendLocation none \
#                     --colorList 'white,g,darkgreen' \
#                     --zMin 0 --zMax 50
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/Kac_cluster_order.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_K36_Kacorder.pdf \
#                     --samplesLabel WT cac-1 \
#                     --startLabel "TSS" \
#                     --sortRegions no \
#                     --heatmapHeight 24 \
#                     --legendLocation none \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/K4_cluster_order.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_K36_K4order.pdf \
#                     --samplesLabel WT cac-1 \
#                     --startLabel "TSS" \
#                     --sortRegions no \
#                     --heatmapHeight 24 \
#                     --legendLocation none \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12

##############################3

# ###cluster of K27 & K36 lost genes
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw \
#    $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#    $MISCDIR/ash1_H3K27me2me3_Rep2.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF1_K27_lost_only.bed $BEDDIR2/CAF1_K36_K27_retain.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_K27_clustered_K27order.pdf \
#                     --samplesLabel WT cac-1 ash-1 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 2 \
#                     --heatmapHeight 24 \
#                     --outFileSortedRegions K27_order.bed \
#                     --legendLocation none \
#                     --colorList 'white,g,darkgreen' \
#                     --zMin 0 --zMax 50
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P149DIR/149-99_ChIP_WT_H3K36me3_Rep3_S123.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF1_K27_lost_only.bed $BEDDIR2/CAF1_K36_K27_retain.bed \
#    --missingDataAsZero --skipZeros -o cluster_test.gz
#
# plotHeatmap -m cluster_test.gz -out K27_genes_CAF-1_K36_clustered_K27order.pdf \
#                     --samplesLabel WT cac-1 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --heatmapHeight 24 \
#                     --outFileSortedRegions K36_order.bed \
#                     --legendLocation none \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# ##applying to H3K4me2 & Kac

#######################
# FIGURE 4
# #RNA-seq
# computeMatrix scale-regions --scale 2 \
#         -S $RNADIR/SRR8269825/SRR8269825_log.bw \
#            /scratch/evt82290/MappingOutputs/Run149/RNA/bigWig/149-115_RNA_cac-1__Rep1_S139/149-115_RNA_cac-1__Rep1_S139_log.bw \
#            $RNADIR/SRR7970630/SRR7970630_log.bw \
#            $RNADIR/SRR10916163/SRR10916163_log.bw \
#            -R $BEDDIR2/Kac_Gain_CAF.bed $BEDDIR2/Kac_Gain_set7_noCAF.bed $BEDDIR2/Kac_no_change.bed $BEDDIR2/Kac_unenriched.bed --skipZeros --missingDataAsZero -o matrix_PRC2_RNA.gz
#
#       plotHeatmap -m matrix_PRC2_RNA.gz -out K27_genes_CAF-1_RNA-seq_Kac_clustered_RNA_order_TEST.pdf \
#               --samplesLabel WT cac-1 cac-2 set-7 \
#               --startLabel "TSS" \
#               --endLabel "TES" \
#               --sortRegions descend \
#               --outFileSortedRegions $BEDDIR2/RNA_order_fig4.bed \
#               --heatmapHeight 20 \
#               --legendLocation none \
#               --colorMap "bwr" \
#               --zMin 0 --zMax 4
#
# # ###Kac
# computeMatrix reference-point --referencePoint TSS -b 1000 -a 800 \
# -S $P150DIR/150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-137_ChIP_cac-2_Kac_Rep2_S152.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-139_ChIP_set-7_Kac_Rep2_S154.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/RNA_order_fig4.bed \
#   --skipZeros --missingDataAsZero -o matrix_CAF-1_Kac_clustered.gz
#
# # $BEDDIR2/Kac_Gain_CAF.bed $BEDDIR2/Kac_Gain_set7_noCAF.bed $BEDDIR2/Kac_no_change.bed $BEDDIR2/Kac_unenriched.bed
#
# plotHeatmap -m matrix_CAF-1_Kac_clustered.gz -out K27_genes_CAF-1_Kac_Kac_clustered_RNA_order.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7  \
#   --startLabel "TSS" \
#   --sortRegions no \
#   --heatmapHeight 20 \
#   --legendLocation none \
#   --colorList 'white, ghostwhite, lavender, mediumslateblue, slateblue' \
#   --zMin 0 --zMax 9

  # --outFileSortedRegions $BEDDIR2/Kac_order_fig4.bed \

#K4
# computeMatrix scale-regions \
# -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
#    $P152DIR/152-106_ChIP_suz12_H3K4me2_Rep2_S130.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/RNA_order_fig4.bed \
#   --skipZeros --missingDataAsZero -o matrix_CAF-1_K4_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_K4_clustered.gz -out K27_genes_CAF-1_H3K4me2_Kac_clustered_RNA_order.pdf \
#   --samplesLabel WT cac-1 cac-2 set-7 \
#   --startLabel "TSS" \
#   --sortRegions no \
#   --heatmapHeight 20 \
#   --legendLocation none \
#   --colorList 'white, violet, magenta' \
#   --zMin 0 --zMax 9
#
# #H3K27me3
#   computeMatrix reference-point --referencePoint TSS -b 1000 -a 800 \
#   -S \
#     "$P136DIR/6147_136-78_ChIP_WT_H3K27me3_CS_Rep2_S77.bin_25.smooth_75Bulk.bw" \
#     "$P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw" \
#     "$P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw" \
#   -R "$BEDDIR2/RNA_order_fig4.bed" --missingDataAsZero --skipZeros -o matrix_K27.mat.gz
#
# plotHeatmap -m matrix_K27.mat.gz -out K27_genes_CAF-1_H3K27me3_Kac_clustered_RNA_order.pdf \
#   --samplesLabel WT cac-1 cac-2 \
#   --startLabel "TSS" \
#   --sortRegions no \
#   --heatmapHeight 20 \
#   --legendLocation none \
#   --colorList 'white,g,darkgreen' \
#   --zMin 0 --zMax 50

######################

#####################
#FIGURE 6

###H3K36me3
##K27 genes
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P152DIR/152-111_ChIP_WT_H3K36me3__S135.bin_25.smooth_75Bulk.bw  \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P152DIR/152-97_ChIP_suz12_H3K36me3_Rep1_S121.bin_25.smooth_75Bulk.bw \
#     $P152DIR/152-101_ChIP_cac-1_suz12_H3K36me3_Rep2_S125.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/K27genes_K36enriched.bed --missingDataAsZero --skipZeros -o K36_K27genes_fig5.gz
#
#     plotHeatmap -m K36_K27genes_fig5.gz -out H3K36me3_K27genes_fig5.pdf \
#                     --samplesLabel WT ash-1 cac-1 suz12 cac-1_suz12 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --outFileSortedRegions CAF-1_K36_order_K27genes.bed \
#                     --sortUsingSamples 1 3 \
#                     --heatmapHeight 24 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12

##ASH-1 methylated
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P152DIR/152-111_ChIP_WT_H3K36me3__S135.bin_25.smooth_75Bulk.bw  \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P152DIR/152-97_ChIP_suz12_H3K36me3_Rep1_S121.bin_25.smooth_75Bulk.bw \
#     $P152DIR/152-101_ChIP_cac-1_suz12_H3K36me3_Rep2_S125.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/ash1_meth_nonK27.bed --missingDataAsZero --skipZeros -o K36_ash1genes_fig5.gz
#
#     plotHeatmap -m K36_ash1genes_fig5.gz -out H3K36me3_ash1_methylated_genes_fig5.pdf \
#                     --samplesLabel WT ash-1 cac-1 suz12 cac-1_suz12 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 3 \
#                     --heatmapHeight 24 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# ##SET-2 methylated
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
# -S $P152DIR/152-111_ChIP_WT_H3K36me3__S135.bin_25.smooth_75Bulk.bw  \
#    $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#    $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#    $P152DIR/152-97_ChIP_suz12_H3K36me3_Rep1_S121.bin_25.smooth_75Bulk.bw \
#    $P152DIR/152-79_ChIP_cac-1_suz12_H3K36me3_Rep3_S79.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/set2_meth_only.bed --missingDataAsZero --skipZeros -o K36_fig5_set2.gz
#
#     plotHeatmap -m K36_fig5_set2.gz -out H3K36me3_set_methylated_only_genes_fig5.pdf \
#                     --samplesLabel WT ash-1 cac-1 suz12 cac-1_suz12 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --heatmapHeight 24 \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12
#
# #Clustered
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#  -S $P152DIR/152-111_ChIP_WT_H3K36me3__S135.bin_25.smooth_75Bulk.bw  \
#     $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#     $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#     $P152DIR/152-97_ChIP_suz12_H3K36me3_Rep1_S121.bin_25.smooth_75Bulk.bw \
#     $P152DIR/152-79_ChIP_cac-1_suz12_H3K36me3_Rep3_S79.bin_25.smooth_75Bulk.bw \
#  -R $BEDDIR2/CAF-1_K36lost.bed $BEDDIR2/CAF-1_K36retain.bed --missingDataAsZero --skipZeros -o K36_clust_fig5_test.gz
#
#     plotHeatmap -m K36_clust_fig5_test.gz -out K36_cluster_fig5.pdf \
#                     --samplesLabel WT ash-1 cac-1 suz12 cac-1_suz12 \
#                     --startLabel "TSS" \
#                     --sortRegions descend \
#                     --sortUsingSamples 1 3 \
#                     --heatmapHeight 24 \
#                     --legendLocation none \
#                     --colorMap "afmhot_r" \
#                     --zMin 0 --zMax 12

###H3K4me2
# computeMatrix scale-regions \
# -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#    $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
#    $P152DIR/152-103_ChIP_suz12_H3K4me2_Rep1_S127.bin_25.smooth_75Bulk.bw \
#    $P152DIR/152-85_ChIP_cac-1_suz12_H3K4me2_Rep3_S85.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/K4_Fig6_order_enriched.bed \
#   --skipZeros --missingDataAsZero -o matrix_CAF-1_K4_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_K4_clustered.gz -out H3K4me2_Figure6.pdf \
#   --samplesLabel WT cac-1 suz-12 cac-1_suz-12 \
#   --startLabel "TSS" \
#   --sortRegions no \
#   --heatmapHeight 5 \
#   --legendLocation none \
#   --whatToShow "heatmap and colorbar" \
#   --colorList 'white, violet, magenta' \
#   --zMin 0 --zMax 9
#
# ###Kac
# computeMatrix reference-point --referencePoint TSS -b 1000 -a 800 \
# -S $P150DIR/150-135_ChIP_WT_Kac_Rep2_S150.bin_25.smooth_75Bulk.bw \
#    $P150DIR/150-136_ChIP_cac-1_Kac_Rep2_S151.bin_25.smooth_75Bulk.bw \
#    $P152DIR/152-80_ChIP_suz12_Kac_Rep1_S80.bin_25.smooth_75Bulk.bw \
#    $P152DIR/152-82_ChIP_cac-1_suz12_Kac_Rep1_S82.bin_25.smooth_75Bulk.bw \
# -R $BEDDIR2/Kac_Fig6_order_enriched.bed \
#   --skipZeros --missingDataAsZero -o matrix_CAF-1_Kac_clustered.gz
#
# plotHeatmap -m matrix_CAF-1_Kac_clustered.gz -out Kac_Figure6.pdf \
#   --samplesLabel WT cac-1 suz-12 cac-1_suz-12 \
#   --startLabel "TSS" \
#   --sortRegions no \
#   --legendLocation none \
#   --heatmapHeight 15 \
#   --whatToShow "heatmap and colorbar" \
#   --colorList 'white, ghostwhite, lavender, mediumslateblue, slateblue' \
#   --zMin 0 --zMax 9

# $BEDDIR2/Kac_Fig6_order_enriched.bed

##########################################
###SUPPLEMENTAL FIGURES
##########################################
###CAF-1 Complementation
##K27
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#                      -S $P152DIR/152-110_ChIP_WT_H3K27me3__S134.bin_25.smooth_75Bulk.bw \
#                         $P136DIR/6147_136-79_ChIP_cac-1_H3K27me3_CS_Rep2_S78.bin_25.smooth_75Bulk.bw \
#                         $P136DIR/6147_136-80_ChIP_cac-2_H3K27me3_CS_Rep2_S79.bin_25.smooth_75Bulk.bw \
#                         $P152DIR/152-116_ChIP_cac-1_comp_H3K27me3_Rep2_S140.bin_25.smooth_75Bulk.bw \
#                         $P149DIR/149-122_ChIP_cac-2_comp_H3K27me3_Rep1_S146.bin_25.smooth_75Bulk.bw \
#                         -R $BEDDIR2/CAF-1_K27lost.bed $BEDDIR2/CAF-1_K27retain.bed --skipZeros --missingDataAsZero -o matrix_K27_cac_comp_K27.gz
#
#                         plotHeatmap -m  matrix_K27_cac_comp_K27.gz -out CAF1_comp_K27_regions.pdf \
#                                         --samplesLabel WT cac-1 cac-2 cac1_comp cac-2_comp \
#                                         --startLabel "TSS" \
#                                         --sortRegions descend \
#                                         --missingDataColor 1 \
#                                         --legendLocation none \
#                                         --colorList "white, g, darkgreen" \
#                                         --zMin 0 --zMax 60
#
#                                         #149-122_ChIP_cac-2_comp_H3K27me3_Rep1_S146.bin_25.smooth_75Bulk.bw
#                                         #149-123_ChIP_cac-2_comp_H3K27me3_Rep1_S147.bin_25.smooth_75Bulk.bw
#
# ##K4
# computeMatrix scale-regions \
#                      -S $P146DIR/146-19_ChIP_WT_H3K4me2_Rep1_S19.bin_25.smooth_75Bulk.bw \
#                         $P146DIR/146-20_ChIP_cac-1_H3K4me2_Rep1_S20.bin_25.smooth_75Bulk.bw \
#                         $P146DIR/146-21_ChIP_cac-2_H3K4me2_Rep1_S21.bin_25.smooth_75Bulk.bw \
#                         $P152DIR/152-90_ChIP_cac-1_comp_H3K4me2_Rep2_S90.bin_25.smooth_75Bulk.bw \
#                         $P149DIR/149-128_ChIP_cac-2_comp_H3K4me2_Rep1_S152.bin_25.smooth_75Bulk.bw \
#                         -R $BEDDIR2/K4_Gain_CAF.bed $BEDDIR2/K4_no_change.bed --skipZeros --missingDataAsZero -o matrix_K4_cac_comp.gz
#
#                         plotHeatmap -m matrix_K4_cac_comp.gz -out CAF1_comp_K4_regions.pdf \
#                                         --samplesLabel WT cac-1 cac-2 cac1_comp cac-2_comp \
#                                         --startLabel "TSS" \
#                                         --sortRegions descend \
#                                         --missingDataColor 1 \
#                                         --heatmapHeight 5 \
#                                         --legendLocation none \
#                                         --colorList 'white, violet, magenta' \
#                                         --zMin 0 --zMax 9
#
# #K36
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#                   -S $P152DIR/152-111_ChIP_WT_H3K36me3__S135.bin_25.smooth_75Bulk.bw \
#                      $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#                      $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#                      $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#                      $P152DIR/152-118_ChIP_cac-1_comp_H3K36me3_Rep2_S142.bin_25.smooth_75Bulk.bw \
#                      $P152DIR/152-120_ChIP_cac-2_comp_H3K36me3_Rep2_S144.bin_25.smooth_75Bulk.bw \
#                         -R $BEDDIR2/K27genes_K36enriched.bed --skipZeros --missingDataAsZero -o matrix_K36_cac_comp.gz
#
#                         plotHeatmap -m matrix_K36_cac_comp.gz -out CAF1_comp_K36_regions.pdf \
#                                         --samplesLabel WT ash-1 cac-1 cac-2 cac1_comp cac-2_comp \
#                                         --startLabel "TSS" \
#                                         --sortRegions descend \
#                                         --missingDataColor 1 \
#                                         --legendLocation none \
#                                         --colorMap "afmhot_r" \
#                                         --zMin 0 --zMax 12
#
# computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
#                   -S $P152DIR/152-111_ChIP_WT_H3K36me3__S135.bin_25.smooth_75Bulk.bw \
#                      $MISCDIR/ash1_K36_ash1paper.bin_25.smooth_75Bulk.bw \
#                      $P149DIR/149-100_ChIP_cac-1_H3K36me3_Rep3_S124.bin_25.smooth_75Bulk.bw \
#                      $P149DIR/149-101_ChIP_cac-2_H3K36me3_Rep3_S125.bin_25.smooth_75Bulk.bw \
#                      $P152DIR/152-118_ChIP_cac-1_comp_H3K36me3_Rep2_S142.bin_25.smooth_75Bulk.bw \
#                      $P152DIR/152-120_ChIP_cac-2_comp_H3K36me3_Rep2_S144.bin_25.smooth_75Bulk.bw \
#                         -R $BEDDIR2/ash1_meth_nonK27.bed --skipZeros --missingDataAsZero -o matrix_K36_ash_cac_comp.gz
#
#                         plotHeatmap -m matrix_K36_ash_cac_comp.gz -out CAF1_comp_K36_regions.pdf \
#                                         --samplesLabel WT ash-1 cac-1 cac-2 cac1_comp cac-2_comp \
#                                         --startLabel "TSS" \
#                                         --sortRegions descend \
#                                         --missingDataColor 1 \
#                                         --legendLocation none \
#                                         --colorMap "afmhot_r" \
#                                         --zMin 0 --zMax 12

###H3K9ME3 & H4K20ME3 ANALYSIS

#H3K9me3
computeMatrix scale-regions -a 500 -b 500 --regionBodyLength 2500 \
 -S $P149DIR/149-104_ChIP_WT_H3K9me3_Rep3_S128.bin_25.smooth_75Bulk.bw \
    $P149DIR/149-105_ChIP_cac-1_H3K9me3_Rep3_S129.bin_25.smooth_75Bulk.bw \
    $P149DIR/149-106_ChIP_cac-2_H3K9me3_Rep3_S130.bin_25.smooth_75Bulk.bw \
    $P149DIR/149-108_ChIP_set-7_Input_Rep3_S132.bin_25.smooth_75Bulk.bw \
 -R $BEDDIR2/WT_H3K9me3_Rep1_peaks.bed --skipZeros --missingDataAsZero -o K9_matrix_PRC2.gz

    plotHeatmap -m K9_matrix_PRC2.gz -out CAF-1_K9_regions.pdf \
                    --samplesLabel WT cac-1 cac-2 set-7 \
                    --startLabel "5'" \
                    --endLabel "3'" \
                    --sortRegions descend \
                    --sortUsingSamples 1 \
                    --missingDataColor 1 \
                    --heatmapHeight 15 \
                    --colorList 'white, mediumblue' \
                    --zMin 0 \

#H4K20me3
computeMatrix scale-regions -a 500 -b 500 --regionBodyLength 2500 \
 -S $P133DIR/133-19_ChIP_WT_H4K20me3_Rep1_S17.bin_25.smooth_75Bulk.bw \
    $P133DIR/133-20_ChIP_cac-1_H4K20me3_Rep1_S18.bin_25.smooth_75Bulk.bw \
    $P133DIR/133-21_ChIP_cac-2_H4K20me3_Rep1_S19.bin_25.smooth_75Bulk.bw \
    $P133DIR/133-22_ChIP_set-7_H4K20me3_Rep1_S20.bin_25.smooth_75Bulk.bw  \
    -R $BEDDIR2/WT_H4K20me3_peaks.bed --skipZeros -o H4K20_matrix_PRC2.gz

    plotHeatmap -m H4K20_matrix_PRC2.gz -out CAF-1_H4K20me3_allpeaks.pdf \
                    --samplesLabel WT cac-1 cac-2 set-7 \
                    --startLabel "5'" \
                    --endLabel "3'" \
                    --sortRegions descend \
                    --sortUsingSamples 1 \
                    --missingDataColor 1 \
                    --colorList 'white, blueviolet' \
                    --zMin 0 \

computeMatrix reference-point --referencePoint TSS -b 800 -a 1500 \
 -S $P133DIR/133-19_ChIP_WT_H4K20me3_Rep1_S17.bin_25.smooth_75Bulk.bw \
    $P133DIR/133-20_ChIP_cac-1_H4K20me3_Rep1_S18.bin_25.smooth_75Bulk.bw \
    $P133DIR/133-21_ChIP_cac-2_H4K20me3_Rep1_S19.bin_25.smooth_75Bulk.bw \
    $P133DIR/133-22_ChIP_set-7_H4K20me3_Rep1_S20.bin_25.smooth_75Bulk.bw  \
    -R $BEDDIR2/K27genes_K36enriched.bed --skipZeros -o H4K20_matrix_PRC2.gz

    plotHeatmap -m H4K20_matrix_PRC2.gz -out CAF-1_H4K20me3_K27_genes_K36enriched.pdf \
                    --samplesLabel WT cac-1 cac-2 set-7 \
                    --startLabel "5'" \
                    --endLabel "3'" \
                    --sortRegions descend \
                    --sortUsingSamples 1 \
                    --missingDataColor 1 \
                    --colorList 'white, blueviolet' \
                    --zMin 0 \

###FILES
# 152-100_ChIP_suz12_H3K36me3_Rep2_S124.bin_25.smooth_75Bulk.bw
# 152-101_ChIP_cac-1_suz12_H3K36me3_Rep2_S125.bin_25.smooth_75Bulk.bw
# 152-102_ChIP_cac-1_cac-2_H3K36me3_Rep2_S126.bin_25.smooth_75Bulk.bw
# 152-103_ChIP_suz12_H3K4me2_Rep1_S127.bin_25.smooth_75Bulk.bw
# 152-104_ChIP_cac-1_suz12_H3K4me2_Rep1_S128.bin_25.smooth_75Bulk.bw
# 152-105_ChIP_cac-1_cac-2_H3K4me2_Rep1_S129.bin_25.smooth_75Bulk.bw
# 152-106_ChIP_suz12_H3K4me2_Rep2_S130.bin_25.smooth_75Bulk.bw
# 152-107_ChIP_cac-1_suz12_H3K4me2_Rep2_S131.bin_25.smooth_75Bulk.bw
# 152-108_ChIP_cac-1_cac-2_H3K4me2_Rep2_S132.bin_25.smooth_75Bulk.bw
# 152-109_ChIP_cac-1_suz12_H3K27me3_Rep1_S133.bin_25.smooth_75Bulk.bw
# 152-110_ChIP_WT_H3K27me3__S134.bin_25.smooth_75Bulk.bw
# 152-111_ChIP_WT_H3K36me3__S135.bin_25.smooth_75Bulk.bw
# 152-112_ChIP_cac-1_suz12_input__S136.bin_25.smooth_75Bulk.bw
# 152-113_ChIP_cac-1_cac-2_input__S137.bin_25.smooth_75Bulk.bw
# 152-114_ChIP_suz12_input__S138.bin_25.smooth_75Bulk.bw
# 152-115_ChIP_cac-1_comp_H3K27me3_Rep1_S139.bin_25.smooth_75Bulk.bw
# 152-116_ChIP_cac-1_comp_H3K27me3_Rep2_S140.bin_25.smooth_75Bulk.bw
# 152-117_ChIP_cac-1_comp_H3K36me3_Rep1_S141.bin_25.smooth_75Bulk.bw
# 152-118_ChIP_cac-1_comp_H3K36me3_Rep2_S142.bin_25.smooth_75Bulk.bw
# 152-119_ChIP_cac-2_comp_H3K36me3_Rep1_S143.bin_25.smooth_75Bulk.bw
# 152-120_ChIP_cac-2_comp_H3K36me3_Rep2_S144.bin_25.smooth_75Bulk.bw
# 152-121_ChIP_cac-2_comp_Kac_Rep1_S145.bin_25.smooth_75Bulk.bw
# 152-122_ChIP_cac-2_comp_Kac_Rep2_S146.bin_25.smooth_75Bulk.bw
# 152-123_ChIP_epr-1_LGIII_nuc_H3K27me3_Rep1_S147.bin_25.smooth_75Bulk.bw
# 152-124_ChIP_epr-1_LGIII_nuc_H3K27me3_Rep2_S148.bin_25.smooth_75Bulk.bw
# 152-125_ChIP_epr-1_LGVI_nuc_H3K27me3_Rep1_S149.bin_25.smooth_75Bulk.bw
# 152-126_ChIP_epr-1_LGVI_nuc_H3K27me3_Rep2_S150.bin_25.smooth_75Bulk.bw
# 152-127_ChIP_cac-1_LGVI_nuc_H3K27me3_Rep1_S151.bin_25.smooth_75Bulk.bw
# 152-128_ChIP_cac-1_LGVI_nuc_H3K27me3_Rep2_S152.bin_25.smooth_75Bulk.bw
# 152-129_ChIP_isw_LGIII_nuc_H3K27me3_Rep1_S153.bin_25.smooth_75Bulk.bw
# 152-130_ChIP_isw_LGIII_nuc_H3K27me3_Rep2_S154.bin_25.smooth_75Bulk.bw
# 152-131_ChIP_qa-suz12_LGVI_single_nuc_0hr_H3K27me3_Rep1_S155.bin_25.smooth_75Bulk.bw
# 152-132_ChIP_qa-suz12_LGVI_single_nuc_4hr_H3K27me3_Rep1_S156.bin_25.smooth_75Bulk.bw
# 152-133_ChIP_qa-suz12_LGVI_single_nuc_24hr_H3K27me3_Rep1_S157.bin_25.smooth_75Bulk.bw
# 152-134_ChIP_qa-suz12_LGVI_single_nuc_0hr_H3K27me3_Rep2_S158.bin_25.smooth_75Bulk.bw
# 152-135_ChIP_qa-suz12_LGVI_single_nuc_4hr_H3K27me3_Rep2_S159.bin_25.smooth_75Bulk.bw
# 152-136_ChIP_qa-suz12_LGVI_single_nuc_24hr_H3K27me3_Rep2_S160.bin_25.smooth_75Bulk.bw
# 152-137_ChIP_qa-suz12_LGVI_single_nuc_0hr_suz12_Rep1_S161.bin_25.smooth_75Bulk.bw
# 152-138_ChIP_qa-suz12_LGVI_single_nuc_4hr_suz12_Rep1_S162.bin_25.smooth_75Bulk.bw
# 152-139_ChIP_qa-suz12_LGVI_single_nuc_24hr_suz12_Rep1_S163.bin_25.smooth_75Bulk.bw
# 152-140_ChIP_qa-suz12_LGVI_single_nuc_0hr_suz12_Rep2_S164.bin_25.smooth_75Bulk.bw
# 152-141_ChIP_qa-suz12_LGVI_single_nuc_4hr_suz12_Rep2_S165.bin_25.smooth_75Bulk.bw
# 152-74_ChIP_suz12_Kac_Rep1_S74.bin_25.smooth_75Bulk.bw
# 152-75_ChIP_cac-1_cac-2_Kac_Rep1_S75.bin_25.smooth_75Bulk.bw
# 152-76_ChIP_cac-1_suz12_Kac_Rep1_S76.bin_25.smooth_75Bulk.bw
# 152-77_ChIP_suz12_H3K36me3_Rep3_S77.bin_25.smooth_75Bulk.bw
# 152-78_ChIP_cac-1_cac-2_H3K36me3_Rep3_S78.bin_25.smooth_75Bulk.bw
# 152-79_ChIP_cac-1_suz12_H3K36me3_Rep3_S79.bin_25.smooth_75Bulk.bw
# 152-80_ChIP_suz12_Kac_Rep1_S80.bin_25.smooth_75Bulk.bw
# 152-81_ChIP_cac-1_cac-2_Kac_Rep1_S81.bin_25.smooth_75Bulk.bw
# 152-82_ChIP_cac-1_suz12_Kac_Rep1_S82.bin_25.smooth_75Bulk.bw
# 152-83_ChIP_suz12_H3K4me2_Rep3_S83.bin_25.smooth_75Bulk.bw
# 152-84_ChIP_cac-1_cac-2_H3K4me2_Rep3_S84.bin_25.smooth_75Bulk.bw
# 152-85_ChIP_cac-1_suz12_H3K4me2_Rep3_S85.bin_25.smooth_75Bulk.bw
# 152-86_ChIP_suz12_input__S86.bin_25.smooth_75Bulk.bw
# 152-87_ChIP_cac-1_cac-2_input__S87.bin_25.smooth_75Bulk.bw
# 152-88_ChIP_cac-1_suz12_input__S88.bin_25.smooth_75Bulk.bw
# 152-89_ChIP_cac-1_comp_H3K4me2_Rep1_S89.bin_25.smooth_75Bulk.bw
# 152-90_ChIP_cac-1_comp_H3K4me2_Rep2_S90.bin_25.smooth_75Bulk.bw
# 152-91_ChIP_cac-1_comp_FLAG_Rep1_S91.bin_25.smooth_75Bulk.bw
# 152-92_ChIP_cac-1_comp_FLAG_Rep2_S92.bin_25.smooth_75Bulk.bw
# 152-93_ChIP_cac-2_comp_FLAG_Rep1_S93.bin_25.smooth_75Bulk.bw
# 152-94_ChIP_cac-2_comp_FLAG_Rep2_S94.bin_25.smooth_75Bulk.bw
# 152-95_ChIP_cac-1_comp_input_Rep1_S95.bin_25.smooth_75Bulk.bw
# 152-96_ChIP_cac-1_comp_input_Rep2_S96.bin_25.smooth_75Bulk.bw
# 152-97_ChIP_suz12_H3K36me3_Rep1_S121.bin_25.smooth_75Bulk.bw
# 152-98_ChIP_cac-1_suz12_H3K36me3_Rep1_S122.bin_25.smooth_75Bulk.bw
# 152-99_ChIP_cac-1_cac-2_H3K36me3_Rep1_S123.bin_25.smooth_75Bulk.bw
# 152-N20_ATAC_WT__Rep5_S116.bin_25.smooth_75Bulk.bw
# 152-N21_ATAC_cac-1__Rep5_S117.bin_25.smooth_75Bulk.bw
# 152-N22_ATAC_cac-2__Rep5_S118.bin_25.smooth_75Bulk.bw
# 152-N23_ATAC_cac-1_suz12__Rep1_S119.bin_25.smooth_75Bulk.bw
# 152-N24_ATAC_set-7__Rep5_S120.bin_25.smooth_75Bulk.bw
