#!/bin/bash
#SBATCH --job-name=featureCounts
#SBATCH --partition=batch
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=evt82290@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=20gb
#SBATCH --time=8:00:00
#SBATCH --output=../RNAseqMap/logs/featureCounts.%j.out
#SBATCH --error=../RNAseqMap/logs/featureCounts.%j.err

#This code will only be used for building a count file across multiple Samples/Strains

cd $SLURM_SUBMIT_DIR

THREADS=2

#Make & Assign Directories
BAMDIR="/scratch/evt82290/RNAseq/qa-suz12/bamFiles"
B149DIR="/scratch/evt82290/MappingOutputs/Run149/RNA/bamFiles"
OUTDIR="/scratch/evt82290/RNAseq/qa-suz12/counts"

# #if output directory doesn't exist, create it
if [ ! -d $OUTDIR ]
then
    mkdir -p $OUTDIR
fi
###
# /scratch/evt82290/RNAseq/CAF-1_Heatmap/bamFiles/SRR7970630/SRR7970630_Aligned.sortedByCoord.out.bam
# /scratch/evt82290/RNAseq/CAF-1_Heatmap/bamFiles/SRR7970630/SRR7970630_Aligned.sortedByCoord.out.bam
#Run featureCounts
module load Subread/

featureCounts -T $THREADS \
-p \
-t CDS \
-g gene_name \
-s 0 --primary \
-a /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_000182925.2_NC12_genomic_GFFtoGTFconversion.gtf \
-o $OUTDIR/readcounts_newseq.txt \
$BAMDIR/SRR8444037/SRR9027658_Aligned.sortedByCoord.out.bam \
$BAMDIR/SRR8444038/SRR9027689_Aligned.sortedByCoord.out.bam \
$BAMDIR/SRR8444043/SRR9027759_Aligned.sortedByCoord.out.bam \
$BAMDIR/SRR8269825/SRR8269825_Aligned.sortedByCoord.out.bam \
$BAMDIR/SRR8269775/SRR8269775_Aligned.sortedByCoord.out.bam \
$BAMDIR/SRR8269782/SRR8269782_Aligned.sortedByCoord.out.bam \
$BAMDIR/SRR8269810/SRR8269810_Aligned.sortedByCoord.out.bam \
$B149DIR/149-89_RNA_WT_24hrqa__Rep3_S89/149-89_RNA_WT_24hrqa__Rep3_S89_Aligned.sortedByCoord.out.bam \
$B149DIR/149-88_RNA_WT_24hrqa__Rep2_S88/149-88_RNA_WT_24hrqa__Rep2_S88_Aligned.sortedByCoord.out.bam \
$B149DIR/149-84_RNA_WT__Rep1_S84/149-84_RNA_WT__Rep1_S84_Aligned.sortedByCoord.out.bam \
$B149DIR/149-85_RNA_WT__Rep2_S85/149-85_RNA_WT__Rep2_S85_Aligned.sortedByCoord.out.bam \
$B149DIR/149-86_RNA_WT__Rep2_S86/149-86_RNA_WT__Rep3_S86_Aligned.sortedByCoord.out.bam \
$B149DIR/149-87_RNA_WT_24hrqa__Rep1_S87/149-87_RNA_WT_24hrqa__Rep1_S87_Aligned.sortedByCoord.out.bam \
$B149DIR/149-90_RNA_qa-suz12__Rep1_S90/149-90_RNA_qa-suz12__Rep1_S90_Aligned.sortedByCoord.out.bam \
$B149DIR/149-91_RNA_qa-suz12__Rep2_S91/149-91_RNA_qa-suz12__Rep2_S91_Aligned.sortedByCoord.out.bam \
$B149DIR/149-92_RNA_qa-suz12__Rep3_S92/149-92_RNA_qa-suz12__Rep3_S92_Aligned.sortedByCoord.out.bam \
$B149DIR/149-93_RNA_qa-suz12_24hrqa__Rep1_S93/149-93_RNA_qa-suz12_24hrqa__Rep1_S93_Aligned.sortedByCoord.out.bam \
$B149DIR/149-94_RNA_qa-suz12_24hrqa__Rep2_S94/149-94_RNA_qa-suz12_24hrqa__Rep2_S94_Aligned.sortedByCoord.out.bam \
$B149DIR/149-95_RNA_qa-suz12_24hrqa__Rep3_S95/149-95_RNA_qa-suz12_24hrqa__Rep3_S95_Aligned.sortedByCoord.out.bam
